In [1]:
import numpy as np  
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix

In [2]:
df = pd.read_csv('/home/yogendra/Documents/MedTechProject/Medtechproject/MedTech_Masterchart - final .csv')

In [3]:
df.shape

(226, 328)

In [4]:
df.head()

,S.no,Age,weight,height,Pulse rate,Pain,staging (TNM),Vata,Pitta,Kapha,...,K_Q62.2,K_Q63,K_Q64,K_Q65_final,K_Q65,K_Q65.1,K_Q66_final,K_Q66,K_Q66.1,K_Q67
0,1,60,75,168,73,5,T2N2cM0,25.2,24.4,50.4,...,0.5,1,1,1,0,1,0,0,0,1
1,2,61,65,165,91,6,T3N1M0,38.2,37.9,23.9,...,0.0,0,0,1,0,1,1,0,1,0
2,3,56,70,170,88,2,T2N0M0,29.1,32.2,38.8,...,0.5,1,1,1,0,1,0,0,0,0
3,4,46,67,185,72,7,T4bN2cM0,29.5,24.0,46.5,...,0.5,1,1,1,0,1,0,0,0,1
4,5,63,67,185,85,3,T2N0M0,38.9,21.7,39.3,...,0.5,1,1,1,0,1,0,0,0,1

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 226 entries, 0 to 225
Columns: 328 entries, S.no to K_Q67
dtypes: float64(54), int64(273), object(1)
memory usage: 579.2+ KB

In [6]:
print(df.isnull().sum().sort_values(ascending=False).head(30))

P_Q16          141
P_Q19          105
V_Q9            61
P_Q9            61
V_Q18           55
K_Q4            11
V_Q4            11
P_Q13           10
K_Q13           10
P_Q59.1          0
P_Q59_final      0
P_Q58            0
P_Q57            0
P_Q56.4          0
P_Q56.3          0
P_Q56.2          0
P_Q56.1          0
P_Q56            0
P_Q56_final      0
P_Q55            0
P_Q54            0
P_Q53.1          0
P_Q53            0
P_Q52            0
P_Q59            0
K_Q3             0
K_Q2.1           0
K_Q2             0
K_Q2_final       0
K_Q1             0
dtype: int64

In [7]:
# We'll handle missing values inside model pipelines to avoid leakage.
print('Missing values (top 30):')
print(df.isnull().sum().sort_values(ascending=False).head(30))

Missing values (top 30):
P_Q16          141
P_Q19          105
V_Q9            61
P_Q9            61
V_Q18           55
K_Q4            11
V_Q4            11
P_Q13           10
K_Q13           10
P_Q59.1          0
P_Q59_final      0
P_Q58            0
P_Q57            0
P_Q56.4          0
P_Q56.3          0
P_Q56.2          0
P_Q56.1          0
P_Q56            0
P_Q56_final      0
P_Q55            0
P_Q54            0
P_Q53.1          0
P_Q53            0
P_Q52            0
P_Q59            0
K_Q3             0
K_Q2.1           0
K_Q2             0
K_Q2_final       0
K_Q1             0
dtype: int64

In [8]:
# Get all column names
cols = df.columns

# Columns to keep
keep_cols = []

for col in cols:
    # If it's a "_final" column → always keep
    if col.endswith('_final'):
        keep_cols.append(col)
    else:
        # Check if corresponding _final exists
        base = col.split('.')[0]  # handles K_Q65.1
        final_col = base + '_final'
        
        if final_col not in cols:
            keep_cols.append(col)

# Keep only selected columns
df = df[keep_cols]

In [9]:
df.head()

,S.no,Age,weight,height,Pulse rate,Pain,staging (TNM),Vata,Pitta,Kapha,...,K_Q58,K_Q59_final,K_Q60,K_Q61,K_Q62_final,K_Q63,K_Q64,K_Q65_final,K_Q66_final,K_Q67
0,1,60,75,168,73,5,T2N2cM0,25.2,24.4,50.4,...,0.5,1,1,0.5,1.0,1,1,1,0,1
1,2,61,65,165,91,6,T3N1M0,38.2,37.9,23.9,...,0.5,1,0,0.0,0.0,0,0,1,1,0
2,3,56,70,170,88,2,T2N0M0,29.1,32.2,38.8,...,0.5,1,1,0.5,1.0,1,1,1,0,0
3,4,46,67,185,72,7,T4bN2cM0,29.5,24.0,46.5,...,0.5,1,1,0.5,1.0,1,1,1,0,1
4,5,63,67,185,85,3,T2N0M0,38.9,21.7,39.3,...,0.5,1,1,0.5,1.0,1,1,1,0,1

In [12]:
df.to_csv("data.csv", index=False)

In [13]:
df.shape

(226, 250)

In [14]:
print(df.columns.tolist())

['S.no', 'Age', 'weight', 'height', 'Pulse rate', 'Pain', 'staging (TNM)', 'Vata', 'Pitta', 'Kapha', 'SF 36', 'Value_Q1', 'Value_Q2', 'Value_Q3', 'Value_Q4', 'Value_Q5', 'Value_Q6', 'Value_Q7', 'Value_Q8', 'Value_Q9', 'Value_Q10', 'Value_Q11', 'Value_Q12', 'Value_Q13', 'Value_Q14', 'Value_Q15', 'Value_Q16', 'Value_Q17', 'Value_Q18', 'Value_Q19', 'Value_Q20', 'Value_Q21', 'Value_Q22', 'Value_Q23', 'Value_Q24', 'Value_Q25', 'Value_Q26', 'Value_Q27', 'Value_Q28', 'Value_Q29', 'Value_Q30', 'Value_Q31', 'Value_Q32', 'Value_Q33', 'Value_Q34', 'Value_Q35', 'Value_Q36', 'V_Q1', 'V_Q2_final', 'V_Q3', 'V_Q4', 'V_Q5', 'V_Q6', 'V_Q7', 'V_Q8', 'V_Q9', 'V_Q10', 'V_Q11', 'V_Q12', 'V_Q13', 'V_Q14', 'V_Q15', 'V_Q16', 'V_Q17_final', 'V_Q18', 'V_Q19', 'V_Q20', 'V_Q21_final', 'V_Q22', 'V_Q23', 'V_Q24', 'V_Q25', 'V_Q26', 'V_Q27', 'V_Q28', 'V_Q29', 'V_Q30', 'V_Q31', 'V_Q32', 'V_Q33', 'V_Q34', 'V_Q35', 'V_Q36', 'V_Q37', 'V_Q38', 'V_Q39', 'V_Q40', 'V_Q41', 'V_Q42', 'V_Q43', 'V_Q44', 'V_Q45', 'V_Q46', 'V_Q47', 'V_Q48_final', 'V_Q49', 'V_Q50', 'V_Q51', 'V_Q52', 'V_Q53', 'V_Q54', 'V_Q55', 'V_Q56_final', 'V_Q57_final', 'V_Q58_final', 'V_Q59_final', 'V_Q60_final', 'V_Q61_final', 'V_Q62_final', 'V_Q63', 'V_Q64', 'V_Q65_final', 'V_Q66_final', 'V_Q67', 'P_Q1', 'P_Q2', 'P_Q3', 'P_Q4', 'P_Q5', 'P_Q6', 'P_Q7', 'P_Q8', 'P_Q9', 'P_Q10', 'P_Q11', 'P_Q12', 'P_Q13', 'P_Q14', 'P_Q15', 'P_Q16', 'P_Q17_final', 'P_Q18_final', 'P_Q19', 'P_Q20', 'P_Q21_final', 'P_Q22', 'P_Q23', 'P_Q24', 'P_Q25', 'P_Q26_final', 'P_Q27', 'P_Q28', 'P_Q29', 'P_Q30', 'P_Q31', 'P_Q32', 'P_Q33', 'P_Q34', 'P_Q35', 'P_Q36', 'P_Q37', 'P_Q38', 'P_Q39', 'P_Q40', 'P_Q41', 'P_Q42', 'P_Q43', 'P_Q44', 'P_Q45', 'P_Q46', 'P_Q47', 'P_Q48', 'P_Q49', 'P_Q50', 'P_Q51', 'P_Q52', 'P_Q53-final', 'P_Q53', 'P_Q53.1', 'P_Q54', 'P_Q55', 'P_Q56_final', 'P_Q57', 'P_Q58', 'P_Q59_final', 'P_Q60', 'P_Q61', 'P_Q62_final', 'P_Q63', 'P_Q64', 'P_Q65', 'P_Q66', 'P_Q67', 'K_Q1', 'K_Q2_final', 'K_Q3', 'K_Q4', 'K_Q5', 'K_Q6', 'K_Q7', 'K_Q8', 'K_Q9', 'K_Q10', 'K_Q11', 'K_Q12', 'K_Q13', 'K_Q14', 'K_Q15', 'K_Q16', 'K_Q17_final', 'K_Q18_final', 'K_Q19', 'K_Q20', 'K_Q21', 'K_Q22', 'K_Q23', 'K_Q24', 'K_Q25', 'K_Q26', 'K_Q27', 'K_Q28', 'K_Q29', 'K_Q30', 'K_Q31', 'K_Q32', 'K_Q33', 'K_Q34', 'K_Q35', 'K_Q36', 'K_Q37', 'K_Q38', 'K_Q39', 'K_Q40', 'K_Q41', 'K_Q42_final', 'K_Q43', 'K_Q44', 'K_Q45', 'K_Q46', 'K_Q47', 'K_Q48', 'K_Q49', 'K_Q50', 'K_Q51', 'K_Q52', 'K_Q53', 'K_Q54', 'K_Q55', 'K_Q56_final', 'K_Q57', 'K_Q58', 'K_Q59_final', 'K_Q60', 'K_Q61', 'K_Q62_final', 'K_Q63', 'K_Q64', 'K_Q65_final', 'K_Q66_final', 'K_Q67']

In [15]:
for col in df.columns:
    print(f'{col}: {df[col].dtypes}')

S.no: int64
Age: int64
weight: int64
height: int64
Pulse rate: int64
Pain: int64
staging (TNM): object
Vata: float64
Pitta: float64
Kapha: float64
SF 36: int64
Value_Q1: int64
Value_Q2: int64
Value_Q3: int64
Value_Q4: int64
Value_Q5: int64
Value_Q6: int64
Value_Q7: int64
Value_Q8: int64
Value_Q9: int64
Value_Q10: int64
Value_Q11: int64
Value_Q12: int64
Value_Q13: int64
Value_Q14: int64
Value_Q15: int64
Value_Q16: int64
Value_Q17: int64
Value_Q18: int64
Value_Q19: int64
Value_Q20: int64
Value_Q21: float64
Value_Q22: int64
Value_Q23: float64
Value_Q24: float64
Value_Q25: float64
Value_Q26: float64
Value_Q27: float64
Value_Q28: float64
Value_Q29: float64
Value_Q30: float64
Value_Q31: float64
Value_Q32: int64
Value_Q33: int64
Value_Q34: int64
Value_Q35: int64
Value_Q36: int64
V_Q1: int64
V_Q2_final: int64
V_Q3: int64
V_Q4: float64
V_Q5: int64
V_Q6: int64
V_Q7: int64
V_Q8: int64
V_Q9: float64
V_Q10: int64
V_Q11: int64
V_Q12: int64
V_Q13: int64
V_Q14: int64
V_Q15: int64
V_Q16: int64
V_Q17_final: int64
V_Q18: float64
V_Q19: int64
V_Q20: int64
V_Q21_final: int64
V_Q22: int64
V_Q23: int64
V_Q24: int64
V_Q25: int64
V_Q26: int64
V_Q27: int64
V_Q28: int64
V_Q29: int64
V_Q30: int64
V_Q31: int64
V_Q32: int64
V_Q33: int64
V_Q34: int64
V_Q35: int64
V_Q36: int64
V_Q37: int64
V_Q38: int64
V_Q39: int64
V_Q40: int64
V_Q41: int64
V_Q42: int64
V_Q43: int64
V_Q44: int64
V_Q45: int64
V_Q46: int64
V_Q47: int64
V_Q48_final: int64
V_Q49: int64
V_Q50: int64
V_Q51: int64
V_Q52: int64
V_Q53: int64
V_Q54: int64
V_Q55: int64
V_Q56_final: float64
V_Q57_final: float64
V_Q58_final: int64
V_Q59_final: int64
V_Q60_final: int64
V_Q61_final: float64
V_Q62_final: int64
V_Q63: int64
V_Q64: int64
V_Q65_final: int64
V_Q66_final: int64
V_Q67: int64
P_Q1: int64
P_Q2: int64
P_Q3: int64
P_Q4: int64
P_Q5: int64
P_Q6: int64
P_Q7: int64
P_Q8: int64
P_Q9: float64
P_Q10: int64
P_Q11: int64
P_Q12: int64
P_Q13: float64
P_Q14: int64
P_Q15: int64
P_Q16: float64
P_Q17_final: int64
P_Q18_final: int64
P_Q19: float64
P_Q20: int64
P_Q21_final: int64
P_Q22: int64
P_Q23: int64
P_Q24: int64
P_Q25: int64
P_Q26_final: int64
P_Q27: int64
P_Q28: int64
P_Q29: int64
P_Q30: int64
P_Q31: int64
P_Q32: int64
P_Q33: int64
P_Q34: int64
P_Q35: int64
P_Q36: int64
P_Q37: int64
P_Q38: int64
P_Q39: int64
P_Q40: int64
P_Q41: int64
P_Q42: int64
P_Q43: int64
P_Q44: int64
P_Q45: int64
P_Q46: int64
P_Q47: int64
P_Q48: int64
P_Q49: int64
P_Q50: int64
P_Q51: int64
P_Q52: int64
P_Q53-final: float64
P_Q53: int64
P_Q53.1: float64
P_Q54: float64
P_Q55: int64
P_Q56_final: float64
P_Q57: int64
P_Q58: int64
P_Q59_final: float64
P_Q60: int64
P_Q61: int64
P_Q62_final: int64
P_Q63: int64
P_Q64: int64
P_Q65: int64
P_Q66: int64
P_Q67: int64
K_Q1: int64
K_Q2_final: int64
K_Q3: int64
K_Q4: float64
K_Q5: int64
K_Q6: int64
K_Q7: int64
K_Q8: int64
K_Q9: int64
K_Q10: int64
K_Q11: int64
K_Q12: int64
K_Q13: float64
K_Q14: int64
K_Q15: int64
K_Q16: int64
K_Q17_final: int64
K_Q18_final: int64
K_Q19: int64
K_Q20: int64
K_Q21: int64
K_Q22: int64
K_Q23: int64
K_Q24: int64
K_Q25: int64
K_Q26: int64
K_Q27: int64
K_Q28: int64
K_Q29: int64
K_Q30: int64
K_Q31: int64
K_Q32: int64
K_Q33: int64
K_Q34: int64
K_Q35: int64
K_Q36: int64
K_Q37: int64
K_Q38: int64
K_Q39: int64
K_Q40: int64
K_Q41: int64
K_Q42_final: int64
K_Q43: int64
K_Q44: int64
K_Q45: int64
K_Q46: int64
K_Q47: int64
K_Q48: int64
K_Q49: int64
K_Q50: int64
K_Q51: int64
K_Q52: int64
K_Q53: int64
K_Q54: float64
K_Q55: int64
K_Q56_final: float64
K_Q57: int64
K_Q58: float64
K_Q59_final: int64
K_Q60: int64
K_Q61: float64
K_Q62_final: float64
K_Q63: int64
K_Q64: int64
K_Q65_final: int64
K_Q66_final: int64
K_Q67: int64

In [16]:
df = pd.get_dummies(df['staging (TNM)'])

In [17]:
df

,T1N1M0,T1aN0M0,T1bN0M0,T2N0M0,T2N1M0,T2N2bM0,T2N2cM0,T2N3bM0,T3N0M0,T3N1M0,...,T4N3bM0,T4aN0M0,T4aN1M0,T4aN2aM0,T4aN2bM0,T4aN2cM0,T4aN3bM0,T4bN2cM0,ryT2N1M0,ryT4aN2cM0
0,False,False,False,False,False,False,True,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,True,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,True,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,True,False,False
4,False,False,False,True,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
221,False,False,False,False,False,False,False,False,True,False,...,False,False,False,False,False,False,False,False,False,False
222,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,True,False,False,False,False,False
223,False,False,False,False,False,False,False,False,True,False,...,False,False,False,False,False,False,False,False,False,False
224,False,False,False,False,False,False,False,False,False,True,...,False,False,False,False,False,False,False,False,False,False
225,False,False,False,True,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [18]:
# df['Prakriti'].value_counts()

In [19]:
# df['Prakriti'] = df['Prakriti'].str.upper().str.strip()
# df['Prakriti']  = df['Prakriti'].apply(lambda x: ''.join(sorted(x)) if isinstance(x, str) else x)

# df['Vata'] = df['Prakriti'].apply(lambda x: 1 if 'V' in x else 0)
# df['Pitta'] = df['Prakriti'].apply(lambda x: 1 if 'P' in x else 0)
# df['Kapha'] = df['Prakriti'].apply(lambda x: 1 if 'K' in x else 0)
# df= df.drop('Prakriti', axis=1)

In [20]:
df

,T1N1M0,T1aN0M0,T1bN0M0,T2N0M0,T2N1M0,T2N2bM0,T2N2cM0,T2N3bM0,T3N0M0,T3N1M0,...,T4N3bM0,T4aN0M0,T4aN1M0,T4aN2aM0,T4aN2bM0,T4aN2cM0,T4aN3bM0,T4bN2cM0,ryT2N1M0,ryT4aN2cM0
0,False,False,False,False,False,False,True,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,True,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,True,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,True,False,False
4,False,False,False,True,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
221,False,False,False,False,False,False,False,False,True,False,...,False,False,False,False,False,False,False,False,False,False
222,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,True,False,False,False,False,False
223,False,False,False,False,False,False,False,False,True,False,...,False,False,False,False,False,False,False,False,False,False
224,False,False,False,False,False,False,False,False,False,True,...,False,False,False,False,False,False,False,False,False,False
225,False,False,False,True,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [21]:
# for col in df.columns:
#     print(f'{col}: {df[col].dtypes}')

In [22]:
# df.select_dtypes(include= 'object').columns

In [23]:
# df = df.drop('Prakriti.1', axis=1)
# df.shape

In [24]:
import pandas as pd
import re

def prepare_dataset(df, mode="value"):
    """
    mode options:
    - "value"     → Value_Q1 to Value_Q36
    - "vpk"       → V_Q1 to K_Q67
    - "all"       → Value_Q1 to K_Q67
    """

    # --- 1. Clean column names ---
    df = df.copy()
    df.columns = df.columns.str.strip()

    # Remove .1, .2 duplicates (e.g., K_Q65.1 → K_Q65)
    df.columns = [re.sub(r'\.\d+$', '', col) for col in df.columns]

    # Fix dash issue (P_Q53-final → P_Q53_final)
    df.columns = [col.replace('-', '_') for col in df.columns]

    # Remove duplicate columns
    df = df.loc[:, ~df.columns.duplicated()]

    # --- 2. Define target ---
    if "SF 36" not in df.columns:
        raise ValueError("Target column 'SF 36' not found")

    y = pd.to_numeric(df["SF 36"], errors='coerce')

    # --- 3. Select features based on mode ---
    if mode == "value":
        feature_cols = [col for col in df.columns if col.startswith("Value_Q")]

    elif mode == "vpk":
        feature_cols = [
            col for col in df.columns
            if col.startswith("V_Q") or col.startswith("P_Q") or col.startswith("K_Q")
        ]

    elif mode == "all":
        feature_cols = [
            col for col in df.columns
            if col.startswith("Value_Q")
            or col.startswith("V_Q")
            or col.startswith("P_Q")
            or col.startswith("K_Q")
        ]

    else:
        raise ValueError("Invalid mode. Choose from: value, vpk, all")

    # --- 4. Final dataset ---
    X = df[feature_cols].apply(pd.to_numeric, errors='coerce')

    # Drop rows where target is missing
    mask = y.notna()
    X = X.loc[mask]
    y = y.loc[mask]

    return X, y

In [25]:
X1, y1 = prepare_dataset(df, mode="value")
X2, y2 = prepare_dataset(df, mode="vpk")
X3, y3 = prepare_dataset(df, mode="all")

ValueError: Target column 'SF 36' not found

In [ ]:
print(X1.shape)
print(X2.shape)
print(X3.shape)

(226, 36)
(226, 202)
(226, 238)

In [26]:
X1

NameError: name 'X1' is not defined

In [27]:
y1

NameError: name 'y1' is not defined

In [28]:
from sklearn.model_selection import train_test_split

def split_data(X, y, random_state=42):
    # 80% train, 10% val, 10% test
    X_train, X_temp, y_train, y_temp = train_test_split(
        X, y, test_size=0.2, random_state=random_state
    )
    X_val, X_test, y_val, y_test = train_test_split(
        X_temp, y_temp, test_size=0.5, random_state=random_state
    )
    return X_train, X_val, X_test, y_train, y_val, y_test

X1_train, X1_val, X1_test, y1_train, y1_val, y1_test = split_data(X1, y1)
X2_train, X2_val, X2_test, y2_train, y2_val, y2_test = split_data(X2, y2)
X3_train, X3_val, X3_test, y3_train, y3_val, y3_test = split_data(X3, y3)

NameError: name 'X1' is not defined

In [29]:
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression, Ridge, Lasso
from sklearn.ensemble import RandomForestRegressor, HistGradientBoostingRegressor
from sklearn.svm import SVR
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np

def compute_metrics(y_true, y_pred):
    mse = mean_squared_error(y_true, y_pred)
    return {
        'MAE': mean_absolute_error(y_true, y_pred),
        'MSE': mse,
        'RMSE': np.sqrt(mse),
        'R2': r2_score(y_true, y_pred)
    }

def print_metrics(name, metrics):
    print(
        f"{name} | MAE: {metrics['MAE']:.4f} | MSE: {metrics['MSE']:.4f} | "
        f"RMSE: {metrics['RMSE']:.4f} | R2: {metrics['R2']:.4f}"
    )

def build_models():
    models = {}

    scaled = Pipeline([
        ('imputer', SimpleImputer(strategy='median'))
        ,('scaler', StandardScaler())
    ])
    unscaled = Pipeline([
        ('imputer', SimpleImputer(strategy='median'))
    ])

    models['Linear'] = Pipeline([('prep', scaled), ('model', LinearRegression())])
    models['Ridge'] = Pipeline([('prep', scaled), ('model', Ridge(alpha=1.0))])
    models['Lasso'] = Pipeline([('prep', scaled), ('model', Lasso(alpha=0.01, max_iter=10000))])
    models['SVR'] = Pipeline([('prep', scaled), ('model', SVR(C=10.0, gamma='scale', epsilon=0.1))])

    models['RandomForest'] = Pipeline([
        ('prep', unscaled),
        ('model', RandomForestRegressor(
            n_estimators=500,
            min_samples_leaf=2,
            random_state=42,
            n_jobs=-1
        ))
    ])

    models['HistGB'] = Pipeline([
        ('prep', unscaled),
        ('model', HistGradientBoostingRegressor(
            random_state=42,
            max_depth=6,
            learning_rate=0.05,
            max_iter=300
        ))
    ])

    try:
        from xgboost import XGBRegressor
        models['XGB'] = Pipeline([
            ('prep', unscaled),
            ('model', XGBRegressor(
                n_estimators=600,
                max_depth=5,
                learning_rate=0.05,
                subsample=0.8,
                colsample_bytree=0.8,
                objective='reg:squarederror',
                random_state=42
            ))
        ])
    except Exception as e:
        print('xgboost not available, skipping XGB:', e)

    return models

def train_select_evaluate(tag, X_train, X_val, X_test, y_train, y_val, y_test):
    models = build_models()
    results = []

    for name, model in models.items():
        model.fit(X_train, y_train)
        val_pred = model.predict(X_val)
        metrics = compute_metrics(y_val, val_pred)
        results.append((name, metrics, model))
        print_metrics(f"{tag} - {name} (val)", metrics)

    # pick best by RMSE on validation set
    best_name, best_metrics, best_model = sorted(results, key=lambda x: x[1]['RMSE'])[0]
    print(f"Best for {tag}: {best_name}")

    # refit best model on train+val, then evaluate on test
    X_full = pd.concat([X_train, X_val])
    y_full = pd.concat([y_train, y_val])
    best_model.fit(X_full, y_full)
    test_pred = best_model.predict(X_test)
    test_metrics = compute_metrics(y_test, test_pred)
    print_metrics(f"{tag} - {best_name} (test)", test_metrics)
    print('')

    return best_name, best_model, test_metrics

# Train + evaluate each feature set
_ = train_select_evalzuate('Value', X1_train, X1_val, X1_test, y1_train, y1_val, y1_test)
_ = train_select_evaluate('VPK', X2_train, X2_val, X2_test, y2_train, y2_val, y2_test)
_ = train_select_evaluate('All', X3_train, X3_val, X3_test, y3_train, y3_val, y3_test)

NameError: name 'train_select_evalzuate' is not defined

In [30]:
# (replaced by consolidated training/evaluation cell above)

In [31]:
# (replaced by consolidated training/evaluation cell above)

In [32]:
# (replaced by consolidated training/evaluation cell above)

In [33]:
# (replaced by consolidated training/evaluation cell above)

In [34]:
# (replaced by consolidated training/evaluation cell above)

In [35]:
# (replaced by consolidated training/evaluation cell above)

In [ ]:
# (replaced by consolidated training/evaluation cell above)

In [ ]:
# (replaced by consolidated training/evaluation cell above)

In [ ]:
# (replaced by consolidated training/evaluation cell above)

In [ ]:
# (replaced by consolidated training/evaluation cell above)