In [2]:
import numpy as np  
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split

from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix

In [3]:
df = pd.read_csv('MedTech_Masterchart - final (1).csv')

In [4]:
df.shape

(226, 329)

In [5]:
df.head()

,S.no,Age,weight,height,Pulse rate,Pain,Site,staging (TNM),Vata,Pitta,...,K_Q62.2,K_Q63,K_Q64,K_Q65_final,K_Q65,K_Q65.1,K_Q66_final,K_Q66,K_Q66.1,K_Q67
0,1,60,75,168,73,5,Hypopharyngeal,T2N2cM0,25.2,24.4,...,0.5,1,1,1,0,1,0,0,0,1
1,2,61,65,165,91,6,Glottis,T3N1M0,38.2,37.9,...,0.0,0,0,1,0,1,1,0,1,0
2,3,56,70,170,88,2,Glottis,T2N0M0,29.1,32.2,...,0.5,1,1,1,0,1,0,0,0,0
3,4,46,67,185,72,7,Oropharyngeal,T4bN2cM0,29.5,24.0,...,0.5,1,1,1,0,1,0,0,0,1
4,5,63,67,185,85,3,Oropharyngeal,T2N0M0,38.9,21.7,...,0.5,1,1,1,0,1,0,0,0,1

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 226 entries, 0 to 225
Columns: 329 entries, S.no to K_Q67
dtypes: float64(54), int64(273), object(2)
memory usage: 581.0+ KB

In [7]:
print(df.isnull().sum().sort_values(ascending=False).head(30))

P_Q16          141
P_Q19          105
V_Q9            61
P_Q9            61
V_Q18           55
K_Q4            11
V_Q4            11
P_Q13           10
K_Q13           10
P_Q56.3          0
P_Q59            0
P_Q59_final      0
P_Q58            0
P_Q57            0
P_Q56.4          0
P_Q56            0
P_Q56.2          0
P_Q56.1          0
P_Q59.2          0
P_Q56_final      0
P_Q55            0
P_Q54            0
P_Q53.1          0
P_Q53            0
P_Q59.1          0
P_Q62_final      0
P_Q60            0
P_Q61            0
K_Q3             0
K_Q2.1           0
dtype: int64

In [8]:
# We'll handle missing values inside model pipelines to avoid leakage.
print('Missing values (top 30):')
print(df.isnull().sum().sort_values(ascending=False).head(30))

Missing values (top 30):
P_Q16          141
P_Q19          105
V_Q9            61
P_Q9            61
V_Q18           55
K_Q4            11
V_Q4            11
P_Q13           10
K_Q13           10
P_Q56.3          0
P_Q59            0
P_Q59_final      0
P_Q58            0
P_Q57            0
P_Q56.4          0
P_Q56            0
P_Q56.2          0
P_Q56.1          0
P_Q59.2          0
P_Q56_final      0
P_Q55            0
P_Q54            0
P_Q53.1          0
P_Q53            0
P_Q59.1          0
P_Q62_final      0
P_Q60            0
P_Q61            0
K_Q3             0
K_Q2.1           0
dtype: int64

In [9]:
# Get all column names
cols = df.columns

# Columns to keep
keep_cols = []

for col in cols:
    # If it's a "_final" column → always keep
    if col.endswith('_final'):
        keep_cols.append(col)
    else:
        # Check if corresponding _final exists
        base = col.split('.')[0]  # handles K_Q65.1
        final_col = base + '_final'
        
        if final_col not in cols:
            keep_cols.append(col)

# Keep only selected columns
df = df[keep_cols]

In [10]:
df.head()

,S.no,Age,weight,height,Pulse rate,Pain,Site,staging (TNM),Vata,Pitta,...,K_Q58,K_Q59_final,K_Q60,K_Q61,K_Q62_final,K_Q63,K_Q64,K_Q65_final,K_Q66_final,K_Q67
0,1,60,75,168,73,5,Hypopharyngeal,T2N2cM0,25.2,24.4,...,0.5,1,1,0.5,1.0,1,1,1,0,1
1,2,61,65,165,91,6,Glottis,T3N1M0,38.2,37.9,...,0.5,1,0,0.0,0.0,0,0,1,1,0
2,3,56,70,170,88,2,Glottis,T2N0M0,29.1,32.2,...,0.5,1,1,0.5,1.0,1,1,1,0,0
3,4,46,67,185,72,7,Oropharyngeal,T4bN2cM0,29.5,24.0,...,0.5,1,1,0.5,1.0,1,1,1,0,1
4,5,63,67,185,85,3,Oropharyngeal,T2N0M0,38.9,21.7,...,0.5,1,1,0.5,1.0,1,1,1,0,1

In [11]:
df.shape

(226, 251)

In [12]:
print(df.columns.tolist())

['S.no', 'Age', 'weight', 'height', 'Pulse rate', 'Pain', 'Site', 'staging (TNM)', 'Vata', 'Pitta', 'Kapha', 'SF 36', 'Value_Q1', 'Value_Q2', 'Value_Q3', 'Value_Q4', 'Value_Q5', 'Value_Q6', 'Value_Q7', 'Value_Q8', 'Value_Q9', 'Value_Q10', 'Value_Q11', 'Value_Q12', 'Value_Q13', 'Value_Q14', 'Value_Q15', 'Value_Q16', 'Value_Q17', 'Value_Q18', 'Value_Q19', 'Value_Q20', 'Value_Q21', 'Value_Q22', 'Value_Q23', 'Value_Q24', 'Value_Q25', 'Value_Q26', 'Value_Q27', 'Value_Q28', 'Value_Q29', 'Value_Q30', 'Value_Q31', 'Value_Q32', 'Value_Q33', 'Value_Q34', 'Value_Q35', 'Value_Q36', 'V_Q1', 'V_Q2_final', 'V_Q3', 'V_Q4', 'V_Q5', 'V_Q6', 'V_Q7', 'V_Q8', 'V_Q9', 'V_Q10', 'V_Q11', 'V_Q12', 'V_Q13', 'V_Q14', 'V_Q15', 'V_Q16', 'V_Q17_final', 'V_Q18', 'V_Q19', 'V_Q20', 'V_Q21_final', 'V_Q22', 'V_Q23', 'V_Q24', 'V_Q25', 'V_Q26', 'V_Q27', 'V_Q28', 'V_Q29', 'V_Q30', 'V_Q31', 'V_Q32', 'V_Q33', 'V_Q34', 'V_Q35', 'V_Q36', 'V_Q37', 'V_Q38', 'V_Q39', 'V_Q40', 'V_Q41', 'V_Q42', 'V_Q43', 'V_Q44', 'V_Q45', 'V_Q46', 'V_Q47', 'V_Q48_final', 'V_Q49', 'V_Q50', 'V_Q51', 'V_Q52', 'V_Q53', 'V_Q54', 'V_Q55', 'V_Q56_final', 'V_Q57_final', 'V_Q58_final', 'V_Q59_final', 'V_Q60_final', 'V_Q61_final', 'V_Q62_final', 'V_Q63', 'V_Q64', 'V_Q65_final', 'V_Q66_final', 'V_Q67', 'P_Q1', 'P_Q2', 'P_Q3', 'P_Q4', 'P_Q5', 'P_Q6', 'P_Q7', 'P_Q8', 'P_Q9', 'P_Q10', 'P_Q11', 'P_Q12', 'P_Q13', 'P_Q14', 'P_Q15', 'P_Q16', 'P_Q17_final', 'P_Q18_final', 'P_Q19', 'P_Q20', 'P_Q21_final', 'P_Q22', 'P_Q23', 'P_Q24', 'P_Q25', 'P_Q26_final', 'P_Q27', 'P_Q28', 'P_Q29', 'P_Q30', 'P_Q31', 'P_Q32', 'P_Q33', 'P_Q34', 'P_Q35', 'P_Q36', 'P_Q37', 'P_Q38', 'P_Q39', 'P_Q40', 'P_Q41', 'P_Q42', 'P_Q43', 'P_Q44', 'P_Q45', 'P_Q46', 'P_Q47', 'P_Q48', 'P_Q49', 'P_Q50', 'P_Q51', 'P_Q52', 'P_Q53-final', 'P_Q53', 'P_Q53.1', 'P_Q54', 'P_Q55', 'P_Q56_final', 'P_Q57', 'P_Q58', 'P_Q59_final', 'P_Q60', 'P_Q61', 'P_Q62_final', 'P_Q63', 'P_Q64', 'P_Q65', 'P_Q66', 'P_Q67', 'K_Q1', 'K_Q2_final', 'K_Q3', 'K_Q4', 'K_Q5', 'K_Q6', 'K_Q7', 'K_Q8', 'K_Q9', 'K_Q10', 'K_Q11', 'K_Q12', 'K_Q13', 'K_Q14', 'K_Q15', 'K_Q16', 'K_Q17_final', 'K_Q18_final', 'K_Q19', 'K_Q20', 'K_Q21', 'K_Q22', 'K_Q23', 'K_Q24', 'K_Q25', 'K_Q26', 'K_Q27', 'K_Q28', 'K_Q29', 'K_Q30', 'K_Q31', 'K_Q32', 'K_Q33', 'K_Q34', 'K_Q35', 'K_Q36', 'K_Q37', 'K_Q38', 'K_Q39', 'K_Q40', 'K_Q41', 'K_Q42_final', 'K_Q43', 'K_Q44', 'K_Q45', 'K_Q46', 'K_Q47', 'K_Q48', 'K_Q49', 'K_Q50', 'K_Q51', 'K_Q52', 'K_Q53', 'K_Q54', 'K_Q55', 'K_Q56_final', 'K_Q57', 'K_Q58', 'K_Q59_final', 'K_Q60', 'K_Q61', 'K_Q62_final', 'K_Q63', 'K_Q64', 'K_Q65_final', 'K_Q66_final', 'K_Q67']

In [13]:
for col in df.columns:
    print(f'{col}: {df[col].dtypes}')

S.no: int64
Age: int64
weight: int64
height: int64
Pulse rate: int64
Pain: int64
Site: object
staging (TNM): object
Vata: float64
Pitta: float64
Kapha: float64
SF 36: int64
Value_Q1: int64
Value_Q2: int64
Value_Q3: int64
Value_Q4: int64
Value_Q5: int64
Value_Q6: int64
Value_Q7: int64
Value_Q8: int64
Value_Q9: int64
Value_Q10: int64
Value_Q11: int64
Value_Q12: int64
Value_Q13: int64
Value_Q14: int64
Value_Q15: int64
Value_Q16: int64
Value_Q17: int64
Value_Q18: int64
Value_Q19: int64
Value_Q20: int64
Value_Q21: float64
Value_Q22: int64
Value_Q23: float64
Value_Q24: float64
Value_Q25: float64
Value_Q26: float64
Value_Q27: float64
Value_Q28: float64
Value_Q29: float64
Value_Q30: float64
Value_Q31: float64
Value_Q32: int64
Value_Q33: int64
Value_Q34: int64
Value_Q35: int64
Value_Q36: int64
V_Q1: int64
V_Q2_final: int64
V_Q3: int64
V_Q4: float64
V_Q5: int64
V_Q6: int64
V_Q7: int64
V_Q8: int64
V_Q9: float64
V_Q10: int64
V_Q11: int64
V_Q12: int64
V_Q13: int64
V_Q14: int64
V_Q15: int64
V_Q16: int64
V_Q17_final: int64
V_Q18: float64
V_Q19: int64
V_Q20: int64
V_Q21_final: int64
V_Q22: int64
V_Q23: int64
V_Q24: int64
V_Q25: int64
V_Q26: int64
V_Q27: int64
V_Q28: int64
V_Q29: int64
V_Q30: int64
V_Q31: int64
V_Q32: int64
V_Q33: int64
V_Q34: int64
V_Q35: int64
V_Q36: int64
V_Q37: int64
V_Q38: int64
V_Q39: int64
V_Q40: int64
V_Q41: int64
V_Q42: int64
V_Q43: int64
V_Q44: int64
V_Q45: int64
V_Q46: int64
V_Q47: int64
V_Q48_final: int64
V_Q49: int64
V_Q50: int64
V_Q51: int64
V_Q52: int64
V_Q53: int64
V_Q54: int64
V_Q55: int64
V_Q56_final: float64
V_Q57_final: float64
V_Q58_final: int64
V_Q59_final: int64
V_Q60_final: int64
V_Q61_final: float64
V_Q62_final: int64
V_Q63: int64
V_Q64: int64
V_Q65_final: int64
V_Q66_final: int64
V_Q67: int64
P_Q1: int64
P_Q2: int64
P_Q3: int64
P_Q4: int64
P_Q5: int64
P_Q6: int64
P_Q7: int64
P_Q8: int64
P_Q9: float64
P_Q10: int64
P_Q11: int64
P_Q12: int64
P_Q13: float64
P_Q14: int64
P_Q15: int64
P_Q16: float64
P_Q17_final: int64
P_Q18_final: int64
P_Q19: float64
P_Q20: int64
P_Q21_final: int64
P_Q22: int64
P_Q23: int64
P_Q24: int64
P_Q25: int64
P_Q26_final: int64
P_Q27: int64
P_Q28: int64
P_Q29: int64
P_Q30: int64
P_Q31: int64
P_Q32: int64
P_Q33: int64
P_Q34: int64
P_Q35: int64
P_Q36: int64
P_Q37: int64
P_Q38: int64
P_Q39: int64
P_Q40: int64
P_Q41: int64
P_Q42: int64
P_Q43: int64
P_Q44: int64
P_Q45: int64
P_Q46: int64
P_Q47: int64
P_Q48: int64
P_Q49: int64
P_Q50: int64
P_Q51: int64
P_Q52: int64
P_Q53-final: float64
P_Q53: int64
P_Q53.1: float64
P_Q54: float64
P_Q55: int64
P_Q56_final: float64
P_Q57: int64
P_Q58: int64
P_Q59_final: float64
P_Q60: int64
P_Q61: int64
P_Q62_final: int64
P_Q63: int64
P_Q64: int64
P_Q65: int64
P_Q66: int64
P_Q67: int64
K_Q1: int64
K_Q2_final: int64
K_Q3: int64
K_Q4: float64
K_Q5: int64
K_Q6: int64
K_Q7: int64
K_Q8: int64
K_Q9: int64
K_Q10: int64
K_Q11: int64
K_Q12: int64
K_Q13: float64
K_Q14: int64
K_Q15: int64
K_Q16: int64
K_Q17_final: int64
K_Q18_final: int64
K_Q19: int64
K_Q20: int64
K_Q21: int64
K_Q22: int64
K_Q23: int64
K_Q24: int64
K_Q25: int64
K_Q26: int64
K_Q27: int64
K_Q28: int64
K_Q29: int64
K_Q30: int64
K_Q31: int64
K_Q32: int64
K_Q33: int64
K_Q34: int64
K_Q35: int64
K_Q36: int64
K_Q37: int64
K_Q38: int64
K_Q39: int64
K_Q40: int64
K_Q41: int64
K_Q42_final: int64
K_Q43: int64
K_Q44: int64
K_Q45: int64
K_Q46: int64
K_Q47: int64
K_Q48: int64
K_Q49: int64
K_Q50: int64
K_Q51: int64
K_Q52: int64
K_Q53: int64
K_Q54: float64
K_Q55: int64
K_Q56_final: float64
K_Q57: int64
K_Q58: float64
K_Q59_final: int64
K_Q60: int64
K_Q61: float64
K_Q62_final: float64
K_Q63: int64
K_Q64: int64
K_Q65_final: int64
K_Q66_final: int64
K_Q67: int64

In [14]:
df['Site'].value_counts()

Site
Oral cavity                 62
Supraglottic                39
Glottic                     33
Hypopharyngeal              30
Oropharyngeal               23
Sinonasal carcinoma         10
Nasopharyngeal Carcinoma     8
Maxillary sinus              5
Sinonasal Carcinoma          4
Glottis                      3
Esophagus                    2
Esophageal                   1
Sinonasal chondrosarcoma     1
Oropharynx                   1
sinonasal carcinoma          1
Sinonasal Sarcoma            1
Nasopharyngeal carcinoma     1
Transglottic                 1
Name: count, dtype: int64

In [19]:
import re
import numpy as np
import pandas as pd
from sklearn.preprocessing import LabelEncoder

def split_tnm_into_t_n(raw, keep_suffixes=False):
    """
    Extracts T and N from a raw TNM string.

    Examples:
        T2aN1bM0  ->  T2, N1   (default)
        T4bN2cM1  ->  T4, N2   (default)
        TisN0M0   ->  Tis, N0

    If keep_suffixes=True:
        T2a -> T2a
        N1b -> N1b
    """
    if pd.isna(raw):
        return np.nan, np.nan

    s = str(raw).upper().strip()
    s = re.sub(r'[\s\-_\/]+', '', s)
    s = re.sub(r'[^TNM0-9ABCIS]', '', s)

    t_match = re.search(r'T(IS|[0-4][ABC]?)', s)
    n_match = re.search(r'N([0-3][ABC]?)', s)

    if not (t_match and n_match):
        return np.nan, np.nan

    t_tok = t_match.group(1)
    n_tok = n_match.group(1)

    # T label
    if t_tok == "IS":
        t_label = "Tis"
    else:
        t_base = t_tok[0]
        t_suffix = t_tok[1:] if len(t_tok) > 1 else ""
        t_label = f"T{t_base}{t_suffix.lower()}" if keep_suffixes and t_suffix else f"T{t_base}"

    # N label
    n_base = n_tok[0]
    n_suffix = n_tok[1:] if len(n_tok) > 1 else ""
    n_label = f"N{n_base}{n_suffix.lower()}" if keep_suffixes and n_suffix else f"N{n_base}"

    return t_label, n_label


def add_tn_columns(df, stage_col="staging (TNM)", keep_suffixes=False):
    """
    Adds:
      - T_stage : encoded T label
      - N_stage : encoded N label

    Also returns the fitted encoders.
    """
    df = df.copy()

    if stage_col not in df.columns:
        raise ValueError(f"Column '{stage_col}' not found")

    parsed = df[stage_col].apply(lambda x: split_tnm_into_t_n(x, keep_suffixes=keep_suffixes))
    parsed_df = pd.DataFrame(parsed.tolist(), columns=["T_label", "N_label"], index=df.index)

    df = pd.concat([df, parsed_df], axis=1)

    # keep only rows where both T and N were successfully parsed
    mask = df["T_label"].notna() & df["N_label"].notna()
    df = df.loc[mask].copy()

    t_le = LabelEncoder()
    n_le = LabelEncoder()

    df["T_stage"] = t_le.fit_transform(df["T_label"].astype(str))
    df["N_stage"] = n_le.fit_transform(df["N_label"].astype(str))

    # remove helper string columns
    df.drop(columns=["T_label", "N_label"], inplace=True)

    return df, t_le, n_le


# Usage
df, t_le, n_le = add_tn_columns(df, stage_col="staging (TNM)", keep_suffixes=False)

print("T classes:", list(t_le.classes_))
print("N classes:", list(n_le.classes_))
print(df[["staging (TNM)", "T_stage", "N_stage"]].head())

T classes: ['T1', 'T2', 'T3', 'T4']
N classes: ['N0', 'N1', 'N2', 'N3']
  staging (TNM)  T_stage  N_stage
0       T2N2cM0        1        2
1        T3N1M0        2        1
2        T2N0M0        1        0
3      T4bN2cM0        3        2
4        T2N0M0        1        0

In [20]:
df

,S.no,Age,weight,height,Pulse rate,Pain,Site,staging (TNM),Vata,Pitta,...,K_Q60,K_Q61,K_Q62_final,K_Q63,K_Q64,K_Q65_final,K_Q66_final,K_Q67,T_stage,N_stage
0,1,60,75,168,73,5,Hypopharyngeal,T2N2cM0,25.2,24.4,...,1,0.5,1.0,1,1,1,0,1,1,2
1,2,61,65,165,91,6,Glottis,T3N1M0,38.2,37.9,...,0,0.0,0.0,0,0,1,1,0,2,1
2,3,56,70,170,88,2,Glottis,T2N0M0,29.1,32.2,...,1,0.5,1.0,1,1,1,0,0,1,0
3,4,46,67,185,72,7,Oropharyngeal,T4bN2cM0,29.5,24.0,...,1,0.5,1.0,1,1,1,0,1,3,2
4,5,63,67,185,85,3,Oropharyngeal,T2N0M0,38.9,21.7,...,1,0.5,1.0,1,1,1,0,1,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
221,222,61,75,176,76,3,Hypopharyngeal,T3N0M0,29.5,24.0,...,1,0.5,1.0,1,1,1,0,1,2,0
222,223,51,69,175,71,3,Oral cavity,T4aN2bM0,29.3,31.0,...,1,0.5,1.0,1,1,1,0,0,3,2
223,224,70,61,166,77,5,Glottic,T3N0M0,38.9,21.7,...,1,0.5,1.0,1,1,1,0,1,2,0
224,225,75,52,176,74,3,Oropharyngeal,T3N1M0,36.6,23.9,...,1,0.5,1.0,1,1,1,0,1,2,1
225,226,65,69,175,75,5,Oral cavity,T2N0M0,48.4,34.3,...,0,0.0,0.0,0,0,1,1,0,1,0

In [22]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import MinMaxScaler

# -----------------------------
# 1. Define numeric columns
# -----------------------------
numeric_cols = ["Pain", "weight", "height", "Pulse rate"]

# Ensure numeric conversion
df[numeric_cols] = df[numeric_cols].apply(pd.to_numeric, errors="coerce")

# -----------------------------
# 2. Filter valid rows
# -----------------------------
# Now we use T_stage and N_stage instead of stage_clean
required_cols = ["T_stage", "N_stage"] + numeric_cols

mask = pd.Series(True, index=df.index)

for col in required_cols:
    mask &= df[col].notna()

df = df.loc[mask].copy()

print("After filtering:", df.shape)

# -----------------------------
# 3. Min-Max scaling (replace original columns)
# -----------------------------
scaler = MinMaxScaler()
df[numeric_cols] = scaler.fit_transform(df[numeric_cols])

# -----------------------------
# Final dataset ready
# -----------------------------
print("\nFinal shape:", df.shape)
print(df[["T_stage", "N_stage"] + numeric_cols].head())

After filtering: (226, 253)

Final shape: (226, 253)
   T_stage  N_stage   Pain    weight    height  Pulse rate
0        1        2  0.500  0.681818  0.387097    0.343750
1        2        1  0.625  0.454545  0.290323    0.625000
2        1        0  0.125  0.568182  0.451613    0.578125
3        3        2  0.750  0.500000  0.935484    0.328125
4        1        0  0.250  0.500000  0.935484    0.531250

In [23]:
from sklearn.preprocessing import OneHotEncoder
import pandas as pd

# ensure df is DataFrame
print(type(df))

encoder = OneHotEncoder(sparse_output=False, handle_unknown='ignore')

encoded = encoder.fit_transform(df[["Site"]])

encoded_df = pd.DataFrame(
    encoded,
    columns=encoder.get_feature_names_out(["Site"])
)

df = pd.concat([df, encoded_df], axis=1)
df.drop("Site", axis=1, inplace=True)

<class 'pandas.core.frame.DataFrame'>

In [24]:
df

,S.no,Age,weight,height,Pulse rate,Pain,staging (TNM),Vata,Pitta,Kapha,...,Site_Oral cavity,Site_Oropharyngeal,Site_Oropharynx,Site_Sinonasal Carcinoma,Site_Sinonasal Sarcoma,Site_Sinonasal carcinoma,Site_Sinonasal chondrosarcoma,Site_Supraglottic,Site_Transglottic,Site_sinonasal carcinoma
0,1,60,0.681818,0.387097,0.343750,0.500,T2N2cM0,25.2,24.4,50.4,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,2,61,0.454545,0.290323,0.625000,0.625,T3N1M0,38.2,37.9,23.9,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,3,56,0.568182,0.451613,0.578125,0.125,T2N0M0,29.1,32.2,38.8,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,4,46,0.500000,0.935484,0.328125,0.750,T4bN2cM0,29.5,24.0,46.5,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,5,63,0.500000,0.935484,0.531250,0.250,T2N0M0,38.9,21.7,39.3,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
221,222,61,0.681818,0.645161,0.390625,0.250,T3N0M0,29.5,24.0,46.5,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
222,223,51,0.545455,0.612903,0.312500,0.250,T4aN2bM0,29.3,31.0,39.7,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
223,224,70,0.363636,0.322581,0.406250,0.500,T3N0M0,38.9,21.7,39.3,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
224,225,75,0.159091,0.645161,0.359375,0.250,T3N1M0,36.6,23.9,39.5,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
225,226,65,0.545455,0.612903,0.375000,0.500,T2N0M0,48.4,34.3,17.3,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [27]:
import pandas as pd
import numpy as np
import re

def prepare_dataset(df, mode="value"):
    """
    mode options:
    - "value" → Value_Q1 to Value_Q36
    - "vpk"   → V_Q*, P_Q*, K_Q*
    - "all"   → Value_Q* + V_Q* + P_Q* + K_Q*

    Returns:
      X        : feature matrix
      y_T      : T_stage
      y_N      : N_stage
      y_pain   : Pain
    """

    df = df.copy()

    # -----------------------------
    # 1. Clean column names
    # -----------------------------
    df.columns = df.columns.str.strip()
    df.columns = [re.sub(r'\.\d+$', '', col) for col in df.columns]
    df.columns = [col.replace('-', '_') for col in df.columns]
    df = df.loc[:, ~df.columns.duplicated()]

    # -----------------------------
    # 2. Targets
    # -----------------------------
    required_targets = ["T_stage", "N_stage", "Pain"]

    for col in required_targets:
        if col not in df.columns:
            raise ValueError(f"Target column '{col}' not found")

    y_T = pd.to_numeric(df["T_stage"], errors="coerce")
    y_N = pd.to_numeric(df["N_stage"], errors="coerce")
    y_pain = pd.to_numeric(df["Pain"], errors="coerce")

    # Keep only valid rows
    mask = y_T.notna() & y_N.notna() & y_pain.notna()
    df = df.loc[mask].copy()

    y_T = y_T.loc[mask].astype(int)
    y_N = y_N.loc[mask].astype(int)
    y_pain = y_pain.loc[mask].astype(float)

    # -----------------------------
    # 3. Select feature columns
    # -----------------------------
    if mode == "value":
        feature_cols = [col for col in df.columns if col.startswith("Value_Q")]

    elif mode == "vpk":
        feature_cols = [
            col for col in df.columns
            if col.startswith("V_Q") or col.startswith("P_Q") or col.startswith("K_Q")
        ]

    elif mode == "all":
        feature_cols = [
            col for col in df.columns
            if col.startswith("Value_Q")
            or col.startswith("V_Q")
            or col.startswith("P_Q")
            or col.startswith("K_Q")
        ]

    else:
        raise ValueError("Invalid mode. Choose from: value, vpk, all")

    # -----------------------------
    # 4. Add Site encoded columns
    # -----------------------------
    site_cols = [col for col in df.columns if col.startswith("Site_")]

    # -----------------------------
    # 5. Final feature matrix
    # -----------------------------
    final_cols = feature_cols + site_cols

    X = (
        df[final_cols]
        .apply(pd.to_numeric, errors="coerce")
        .replace([np.inf, -np.inf], np.nan)
        .fillna(0.0)
    )

    return (
        np.nan_to_num(np.asarray(X, dtype=np.float32), nan=0.0, posinf=0.0, neginf=0.0),
        np.asarray(y_T),
        np.asarray(y_N),
        np.asarray(y_pain),
    )


# -----------------------------
# Example usage
# -----------------------------
X1, y_T1, y_N1, y_pain1 = prepare_dataset(df, mode="value")
X2, y_T2, y_N2, y_pain2 = prepare_dataset(df, mode="vpk")
X3, y_T3, y_N3, y_pain3 = prepare_dataset(df, mode="all")

print(X1.shape, X2.shape, X3.shape)
print("T classes:", len(np.unique(y_T1)))
print("N classes:", len(np.unique(y_N1)))
print("Pain range:", y_pain1.min(), y_pain1.max())

(226, 54) (226, 220) (226, 256)
T classes: 4
N classes: 4
Pain range: 0.0 1.0

In [29]:
y_N1

array([2, 1, 0, 2, 0, 1, 0, 1, 1, 1, 2, 3, 1, 0, 1, 2, 0, 1, 0, 3, 1, 1,
       3, 2, 0, 3, 1, 1, 1, 2, 1, 0, 0, 0, 0, 1, 2, 1, 1, 0, 2, 2, 0, 1,
       0, 1, 2, 1, 0, 2, 0, 2, 1, 1, 1, 2, 0, 0, 2, 1, 1, 1, 1, 1, 0, 0,
       0, 1, 0, 3, 1, 1, 1, 0, 0, 1, 1, 1, 2, 1, 2, 1, 2, 0, 1, 1, 2, 1,
       2, 2, 1, 1, 1, 0, 1, 0, 0, 1, 3, 3, 1, 3, 2, 0, 0, 1, 1, 1, 1, 2,
       1, 0, 2, 1, 3, 2, 1, 2, 1, 2, 1, 1, 2, 0, 1, 0, 1, 1, 1, 1, 0, 1,
       3, 1, 1, 1, 1, 0, 2, 1, 1, 1, 1, 2, 1, 0, 0, 1, 1, 0, 2, 3, 0, 2,
       1, 1, 2, 2, 0, 2, 1, 1, 0, 2, 0, 1, 0, 1, 1, 0, 1, 0, 2, 0, 1, 1,
       2, 1, 2, 1, 1, 2, 0, 1, 2, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 3, 0, 3,
       2, 1, 1, 1, 2, 1, 0, 1, 1, 1, 0, 0, 3, 0, 2, 1, 1, 2, 2, 0, 2, 1,
       2, 0, 2, 0, 1, 0])

In [30]:
import numpy as np
from collections import Counter

def fix_single_sample_classes(X, y_T, y_N, y_pain, min_count=3):
    """
    Ensures each (T, N) class combination has at least `min_count` samples
    by duplicating rows.

    Parameters:
        X       : feature matrix (numpy array)
        y_T     : T_stage labels
        y_N     : N_stage labels
        y_pain  : regression target
        min_count : minimum samples required per class

    Returns:
        X_new, y_T_new, y_N_new, y_pain_new
    """

    X = np.asarray(X)
    y_T = np.asarray(y_T)
    y_N = np.asarray(y_N)
    y_pain = np.asarray(y_pain)

    # 🔥 Combine T and N into joint class
    y_joint = np.array([f"{t}_{n}" for t, n in zip(y_T, y_N)])

    class_counts = Counter(y_joint)

    X_list = [X]
    yT_list = [y_T]
    yN_list = [y_N]
    ypain_list = [y_pain]

    for cls, count in class_counts.items():
        if count < min_count:
            needed = min_count - count

            # indices of this joint class
            idx = np.where(y_joint == cls)[0]

            # duplicate
            dup_idx = np.random.choice(idx, size=needed, replace=True)

            X_list.append(X[dup_idx])
            yT_list.append(y_T[dup_idx])
            yN_list.append(y_N[dup_idx])
            ypain_list.append(y_pain[dup_idx])

    # combine
    X_new = np.vstack(X_list)
    y_T_new = np.concatenate(yT_list)
    y_N_new = np.concatenate(yN_list)
    y_pain_new = np.concatenate(ypain_list)

    return X_new, y_T_new, y_N_new, y_pain_new

In [33]:
import numpy as np
import torch
import torch.nn as nn

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("Using device:", device)


class MultiTaskNet(nn.Module):
    def __init__(
        self,
        input_dim,
        n_T_classes,
        n_N_classes,
        hidden_dims=(64, 32, 16),
        dropout=0.10
    ):
        super().__init__()

        h1, h2, h3 = hidden_dims

        # -----------------------------
        # Shared backbone
        # -----------------------------
        self.shared = nn.Sequential(
            nn.Linear(input_dim, h1),
            nn.ReLU(),
            nn.Dropout(dropout),

            nn.Linear(h1, h2),
            nn.ReLU(),
            nn.Dropout(dropout),

            nn.Linear(h2, h3),
            nn.ReLU()
        )

        # -----------------------------
        # T classification head
        # -----------------------------
        self.T_head = nn.Sequential(
            nn.Linear(h3, h3),
            nn.ReLU(),
            nn.Linear(h3, n_T_classes)
        )

        # -----------------------------
        # N classification head
        # -----------------------------
        self.N_head = nn.Sequential(
            nn.Linear(h3, h3),
            nn.ReLU(),
            nn.Linear(h3, n_N_classes)
        )

        # -----------------------------
        # Pain regression head
        # -----------------------------
        self.pain_head = nn.Sequential(
            nn.Linear(h3, h3),
            nn.ReLU(),
            nn.Linear(h3, 1)
        )

    def forward(self, x):
        shared = self.shared(x)

        T_logits = self.T_head(shared)
        N_logits = self.N_head(shared)
        pain_pred = self.pain_head(shared)

        return T_logits, N_logits, pain_pred


# ---------------------------------------------------
# Build function with 3 architectures
# ---------------------------------------------------
def build_model(input_dim, n_T_classes, n_N_classes, arch="big"):
    """
    arch options:
    - "small" → 32-16-8
    - "big"   → 64-32-16
    - "ultra" → 128-64-32
    """

    if arch == "small":
        hidden_dims = (32, 16, 8)
        dropout = 0.05

    elif arch == "big":
        hidden_dims = (64, 32, 16)
        dropout = 0.10

    elif arch == "ultra":
        hidden_dims = (128, 64, 32)
        dropout = 0.15  # slightly higher to control overfitting

    else:
        raise ValueError("arch must be 'small', 'big', or 'ultra'")

    model = MultiTaskNet(
        input_dim=input_dim,
        n_T_classes=n_T_classes,
        n_N_classes=n_N_classes,
        hidden_dims=hidden_dims,
        dropout=dropout
    )

    return model.to(device)

Using device: cpu

In [34]:
from sklearn.metrics import (
    accuracy_score,
    balanced_accuracy_score,
    f1_score,
    mean_absolute_error,
    mean_squared_error,
    r2_score,
    explained_variance_score,
    confusion_matrix
)
import numpy as np


# ---------------------------------------------------
# Regression metrics (UNCHANGED)
# ---------------------------------------------------
def regression_debug_metrics(y_true, y_pred):
    y_true = np.asarray(y_true).reshape(-1)
    y_pred = np.asarray(y_pred).reshape(-1)

    mse = mean_squared_error(y_true, y_pred)
    rmse = float(np.sqrt(mse))
    mae = mean_absolute_error(y_true, y_pred)
    r2 = r2_score(y_true, y_pred)
    evs = explained_variance_score(y_true, y_pred)

    pred_var = float(np.var(y_pred))
    true_var = float(np.var(y_true))
    resid = y_true - y_pred
    resid_std = float(np.std(resid))

    return {
        "MAE": float(mae),
        "MSE": float(mse),
        "RMSE": rmse,
        "R2": float(r2),
        "ExplainedVariance": float(evs),
        "PredVariance": pred_var,
        "TrueVariance": true_var,
        "ResidualStd": resid_std,
    }


# ---------------------------------------------------
# Classification metrics (for ONE head)
# ---------------------------------------------------
def classification_debug_metrics(y_true, y_pred, y_prob=None):
    y_true = np.asarray(y_true).reshape(-1)
    y_pred = np.asarray(y_pred).reshape(-1)

    acc = accuracy_score(y_true, y_pred)
    bal_acc = balanced_accuracy_score(y_true, y_pred)
    macro_f1 = f1_score(y_true, y_pred, average="macro")

    out = {
        "Accuracy": float(acc),
        "BalancedAccuracy": float(bal_acc),
        "MacroF1": float(macro_f1),
        "ConfusionMatrix": confusion_matrix(y_true, y_pred)
    }

    if y_prob is not None:
        y_prob = np.asarray(y_prob)
        max_conf = np.max(y_prob, axis=1)
        entropy = -np.sum(y_prob * np.log(np.clip(y_prob, 1e-12, 1.0)), axis=1)

        out["MeanSoftmaxConfidence"] = float(np.mean(max_conf))
        out["MedianSoftmaxConfidence"] = float(np.median(max_conf))
        out["MeanEntropy"] = float(np.mean(entropy))

    return out


# ---------------------------------------------------
# Print block for BOTH T and N
# ---------------------------------------------------
def print_metrics_block(title, T_metrics, N_metrics, reg_metrics):
    print(f"\n===== {title} =====")

    # -----------------------------
    # T metrics
    # -----------------------------
    print("\n--- T Classification ---")
    print(
        f"Acc: {T_metrics['Accuracy']:.4f} | "
        f"BalAcc: {T_metrics['BalancedAccuracy']:.4f} | "
        f"MacroF1: {T_metrics['MacroF1']:.4f}"
    )

    if "MeanSoftmaxConfidence" in T_metrics:
        print(
            f"Confidence | Mean: {T_metrics['MeanSoftmaxConfidence']:.4f} | "
            f"Median: {T_metrics['MedianSoftmaxConfidence']:.4f} | "
            f"Entropy: {T_metrics['MeanEntropy']:.4f}"
        )

    print("Confusion matrix (T):\n", T_metrics["ConfusionMatrix"])

    # -----------------------------
    # N metrics
    # -----------------------------
    print("\n--- N Classification ---")
    print(
        f"Acc: {N_metrics['Accuracy']:.4f} | "
        f"BalAcc: {N_metrics['BalancedAccuracy']:.4f} | "
        f"MacroF1: {N_metrics['MacroF1']:.4f}"
    )

    if "MeanSoftmaxConfidence" in N_metrics:
        print(
            f"Confidence | Mean: {N_metrics['MeanSoftmaxConfidence']:.4f} | "
            f"Median: {N_metrics['MedianSoftmaxConfidence']:.4f} | "
            f"Entropy: {N_metrics['MeanEntropy']:.4f}"
        )

    print("Confusion matrix (N):\n", N_metrics["ConfusionMatrix"])

    # -----------------------------
    # Pain regression
    # -----------------------------
    print("\n--- Pain Regression ---")
    print(
        f"MAE: {reg_metrics['MAE']:.4f} | "
        f"RMSE: {reg_metrics['RMSE']:.4f} | "
        f"MSE: {reg_metrics['MSE']:.4f} | "
        f"R2: {reg_metrics['R2']:.4f} | "
        f"EVS: {reg_metrics['ExplainedVariance']:.4f}"
    )

    print(
        f"Variance | Pred: {reg_metrics['PredVariance']:.4f} | "
        f"True: {reg_metrics['TrueVariance']:.4f} | "
        f"ResidualStd: {reg_metrics['ResidualStd']:.4f}"
    )

In [35]:
from collections import Counter
from sklearn.model_selection import train_test_split
from torch.utils.data import TensorDataset, DataLoader

def run_model(
    X,
    y_T,
    y_N,
    y_pain,
    dataset_name="dataset",
    arch="big",
    min_count=3,
    test_size=0.20,
    random_state=42,
    batch_size=16,
    epochs=120,
    lr=3e-3,
    weight_decay=1e-5,
    T_loss_w=1.0,
    N_loss_w=1.0,
    pain_loss_w=0.5
):

    # ---------------------------------------------------
    # 1) Convert to numpy
    # ---------------------------------------------------
    X = np.asarray(X, dtype=np.float32)
    y_T = np.asarray(y_T, dtype=np.int64).reshape(-1)
    y_N = np.asarray(y_N, dtype=np.int64).reshape(-1)
    y_pain = np.asarray(y_pain, dtype=np.float32).reshape(-1, 1)

    print(f"\n--- {dataset_name.upper()} ---")
    print("Original shape:", X.shape)
    print("T class counts:", dict(Counter(y_T)))
    print("N class counts:", dict(Counter(y_N)))

    # ---------------------------------------------------
    # 2) Train/test split (FIRST)
    # ---------------------------------------------------
    X_train, X_test, yT_train, yT_test, yN_train, yN_test, ypain_train, ypain_test = train_test_split(
        X,
        y_T,
        y_N,
        y_pain,
        test_size=test_size,
        random_state=random_state,
        stratify=y_T   # stratify on T (more stable than joint)
    )

    # ---------------------------------------------------
    # 3) Apply replication ONLY on train
    # ---------------------------------------------------
    X_train, yT_train, yN_train, ypain_train = fix_single_sample_classes(
        X_train, yT_train, yN_train, ypain_train, min_count=min_count
    )

    print("Train shape (after balancing):", X_train.shape)
    print("Test shape:", X_test.shape)

    # ---------------------------------------------------
    # 4) DataLoaders
    # ---------------------------------------------------
    X_train_t = torch.tensor(X_train, dtype=torch.float32)
    yT_train_t = torch.tensor(yT_train, dtype=torch.long)
    yN_train_t = torch.tensor(yN_train, dtype=torch.long)
    ypain_train_t = torch.tensor(ypain_train, dtype=torch.float32)

    X_test_t = torch.tensor(X_test, dtype=torch.float32)
    yT_test_t = torch.tensor(yT_test, dtype=torch.long)
    yN_test_t = torch.tensor(yN_test, dtype=torch.long)
    ypain_test_t = torch.tensor(ypain_test, dtype=torch.float32)

    train_ds = TensorDataset(X_train_t, yT_train_t, yN_train_t, ypain_train_t)
    test_ds = TensorDataset(X_test_t, yT_test_t, yN_test_t, ypain_test_t)

    train_loader = DataLoader(train_ds, batch_size=batch_size, shuffle=True)
    test_loader = DataLoader(test_ds, batch_size=batch_size, shuffle=False)

    # ---------------------------------------------------
    # 5) Model
    # ---------------------------------------------------
    n_T_classes = len(np.unique(y_T))
    n_N_classes = len(np.unique(y_N))

    model = build_model(
        input_dim=X.shape[1],
        n_T_classes=n_T_classes,
        n_N_classes=n_N_classes,
        arch=arch
    )

    T_criterion = nn.CrossEntropyLoss()
    N_criterion = nn.CrossEntropyLoss()
    pain_criterion = nn.MSELoss()

    optimizer = torch.optim.AdamW(
        model.parameters(),
        lr=lr,
        weight_decay=weight_decay
    )

    total_steps = max(1, epochs * len(train_loader))
    scheduler = torch.optim.lr_scheduler.OneCycleLR(
        optimizer,
        max_lr=lr,
        total_steps=total_steps,
        pct_start=0.25,
        anneal_strategy="cos",
        div_factor=10.0,
        final_div_factor=100.0
    )

    use_amp = device.type == "cuda"
    scaler = torch.cuda.amp.GradScaler(enabled=use_amp)

    # ---------------------------------------------------
    # 6) Training loop
    # ---------------------------------------------------
    for epoch in range(1, epochs + 1):
        model.train()

        total_loss = 0
        T_correct = 0
        N_correct = 0
        total = 0

        for xb, yTb, yNb, ypb in train_loader:
            xb = xb.to(device)
            yTb = yTb.to(device)
            yNb = yNb.to(device)
            ypb = ypb.to(device).squeeze(-1)

            optimizer.zero_grad(set_to_none=True)

            with torch.cuda.amp.autocast(enabled=use_amp):
                T_logits, N_logits, pain_pred = model(xb)
                pain_pred = pain_pred.squeeze(-1)

                loss_T = T_criterion(T_logits, yTb)
                loss_N = N_criterion(N_logits, yNb)
                loss_pain = pain_criterion(pain_pred, ypb)

                loss = (
                    T_loss_w * loss_T +
                    N_loss_w * loss_N +
                    pain_loss_w * loss_pain
                )

            scaler.scale(loss).backward()
            scaler.step(optimizer)
            scaler.update()
            scheduler.step()

            total_loss += loss.item() * xb.size(0)

            T_pred = torch.argmax(T_logits, dim=1)
            N_pred = torch.argmax(N_logits, dim=1)

            T_correct += (T_pred == yTb).sum().item()
            N_correct += (N_pred == yNb).sum().item()
            total += yTb.size(0)

        print(
            f"Epoch {epoch:03d} | "
            f"Loss: {total_loss/total:.4f} | "
            f"T_acc: {T_correct/total:.4f} | "
            f"N_acc: {N_correct/total:.4f}"
        )

    # ---------------------------------------------------
    # 7) Evaluation
    # ---------------------------------------------------
    model.eval()

    all_T_true, all_T_pred, all_T_prob = [], [], []
    all_N_true, all_N_pred, all_N_prob = [], [], []
    all_pain_true, all_pain_pred = [], []

    with torch.no_grad():
        for xb, yTb, yNb, ypb in test_loader:
            xb = xb.to(device)

            T_logits, N_logits, pain_pred = model(xb)

            T_prob = torch.softmax(T_logits, dim=1)
            N_prob = torch.softmax(N_logits, dim=1)

            all_T_true.extend(yTb.numpy())
            all_T_pred.extend(torch.argmax(T_prob, dim=1).cpu().numpy())
            all_T_prob.extend(T_prob.cpu().numpy())

            all_N_true.extend(yNb.numpy())
            all_N_pred.extend(torch.argmax(N_prob, dim=1).cpu().numpy())
            all_N_prob.extend(N_prob.cpu().numpy())

            all_pain_true.extend(ypb.numpy())
            all_pain_pred.extend(pain_pred.squeeze(-1).cpu().numpy())

    T_metrics = classification_debug_metrics(
        all_T_true, all_T_pred, all_T_prob
    )
    N_metrics = classification_debug_metrics(
        all_N_true, all_N_pred, all_N_prob
    )
    reg_metrics = regression_debug_metrics(
        all_pain_true, all_pain_pred
    )

    print_metrics_block(dataset_name, T_metrics, N_metrics, reg_metrics)

    return {
        "model": model,
        "T_metrics": T_metrics,
        "N_metrics": N_metrics,
        "regression": reg_metrics
    }

In [36]:

# -----------------------------
# VALUE MODE
# -----------------------------
results_value_small = run_model(
    X1, y_T1, y_N1, y_pain1,
    dataset_name="value_small",
    arch="small"
)

results_value_big = run_model(
    X1, y_T1, y_N1, y_pain1,
    dataset_name="value_big",
    arch="big"
)

results_value_ultra = run_model(
    X1, y_T1, y_N1, y_pain1,
    dataset_name="value_ultra",
    arch="ultra"
)


# -----------------------------
# VPK MODE
# -----------------------------
results_vpk_small = run_model(
    X2, y_T2, y_N2, y_pain2,
    dataset_name="vpk_small",
    arch="small"
)

results_vpk_big = run_model(
    X2, y_T2, y_N2, y_pain2,
    dataset_name="vpk_big",
    arch="big"
)

results_vpk_ultra = run_model(
    X2, y_T2, y_N2, y_pain2,
    dataset_name="vpk_ultra",
    arch="ultra"
)


# -----------------------------
# ALL MODE
# -----------------------------
results_all_small = run_model(
    X3, y_T3, y_N3, y_pain3,
    dataset_name="all_small",
    arch="small"
)

results_all_big = run_model(
    X3, y_T3, y_N3, y_pain3,
    dataset_name="all_big",
    arch="big"
)

results_all_ultra = run_model(
    X3, y_T3, y_N3, y_pain3,
    dataset_name="all_ultra",
    arch="ultra"
)

--- VALUE_SMALL ---
Original shape: (226, 54)
T class counts: {1: 35, 2: 133, 3: 53, 0: 5}
N class counts: {2: 48, 1: 106, 0: 58, 3: 14}
Train shape (after balancing): (182, 54)
Test shape: (46, 54)

/var/folders/ff/flzt5myn3x55cy_nz85y_ynr0000gn/T/ipykernel_18667/2434738068.py:114: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = torch.cuda.amp.GradScaler(enabled=use_amp)
/var/folders/ff/flzt5myn3x55cy_nz85y_ynr0000gn/T/ipykernel_18667/2434738068.py:135: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with torch.cuda.amp.autocast(enabled=use_amp):

Epoch 001 | Loss: 2.7791 | T_acc: 0.5824 | N_acc: 0.2582
Epoch 002 | Loss: 2.7588 | T_acc: 0.5824 | N_acc: 0.2582
Epoch 003 | Loss: 2.7416 | T_acc: 0.5824 | N_acc: 0.2582
Epoch 004 | Loss: 2.7262 | T_acc: 0.5824 | N_acc: 0.2582
Epoch 005 | Loss: 2.7086 | T_acc: 0.5824 | N_acc: 0.2582
Epoch 006 | Loss: 2.6886 | T_acc: 0.5824 | N_acc: 0.2582
Epoch 007 | Loss: 2.6676 | T_acc: 0.5824 | N_acc: 0.2582
Epoch 008 | Loss: 2.6417 | T_acc: 0.5824 | N_acc: 0.2582
Epoch 009 | Loss: 2.6060 | T_acc: 0.5824 | N_acc: 0.2582
Epoch 010 | Loss: 2.5543 | T_acc: 0.5824 | N_acc: 0.3956
Epoch 011 | Loss: 2.4547 | T_acc: 0.5824 | N_acc: 0.4835
Epoch 012 | Loss: 2.3456 | T_acc: 0.5824 | N_acc: 0.4835
Epoch 013 | Loss: 2.3118 | T_acc: 0.5824 | N_acc: 0.4780
Epoch 014 | Loss: 2.2984 | T_acc: 0.5824 | N_acc: 0.4835
Epoch 015 | Loss: 2.2870 | T_acc: 0.5824 | N_acc: 0.4835
Epoch 016 | Loss: 2.2815 | T_acc: 0.5824 | N_acc: 0.4835
Epoch 017 | Loss: 2.2764 | T_acc: 0.5824 | N_acc: 0.4835
Epoch 018 | Loss: 2.2594 | T_acc: 0.5824 | N_acc: 0.4835
Epoch 019 | Loss: 2.2701 | T_acc: 0.5824 | N_acc: 0.4835
Epoch 020 | Loss: 2.2738 | T_acc: 0.5824 | N_acc: 0.4835
Epoch 021 | Loss: 2.2694 | T_acc: 0.5824 | N_acc: 0.4835
Epoch 022 | Loss: 2.2318 | T_acc: 0.5824 | N_acc: 0.4835
Epoch 023 | Loss: 2.2192 | T_acc: 0.5824 | N_acc: 0.4835
Epoch 024 | Loss: 2.2220 | T_acc: 0.5824 | N_acc: 0.4835
Epoch 025 | Loss: 2.1983 | T_acc: 0.5824 | N_acc: 0.4835
Epoch 026 | Loss: 2.2075 | T_acc: 0.5824 | N_acc: 0.4835
Epoch 027 | Loss: 2.2347 | T_acc: 0.5824 | N_acc: 0.5000
Epoch 028 | Loss: 2.1809 | T_acc: 0.5824 | N_acc: 0.4780
Epoch 029 | Loss: 2.1495 | T_acc: 0.5824 | N_acc: 0.5000
Epoch 030 | Loss: 2.1650 | T_acc: 0.5824 | N_acc: 0.4890
Epoch 031 | Loss: 2.1748 | T_acc: 0.5824 | N_acc: 0.4560
Epoch 032 | Loss: 2.1479 | T_acc: 0.5824 | N_acc: 0.4835
Epoch 033 | Loss: 2.1386 | T_acc: 0.5824 | N_acc: 0.5055
Epoch 034 | Loss: 2.1310 | T_acc: 0.5824 | N_acc: 0.5000
Epoch 035 | Loss: 2.1251 | T_acc: 0.5824 | N_acc: 0.5055
Epoch 036 | Loss: 2.1144 | T_acc: 0.5824 | N_acc: 0.5055
Epoch 037 | Loss: 2.0815 | T_acc: 0.5824 | N_acc: 0.4945
Epoch 038 | Loss: 2.0945 | T_acc: 0.5879 | N_acc: 0.5275
Epoch 039 | Loss: 2.0865 | T_acc: 0.5989 | N_acc: 0.5110
Epoch 040 | Loss: 2.0630 | T_acc: 0.5769 | N_acc: 0.5385
Epoch 041 | Loss: 2.0896 | T_acc: 0.5659 | N_acc: 0.5275
Epoch 042 | Loss: 2.0563 | T_acc: 0.5934 | N_acc: 0.5330
Epoch 043 | Loss: 2.0475 | T_acc: 0.5989 | N_acc: 0.4945
Epoch 044 | Loss: 2.0308 | T_acc: 0.6044 | N_acc: 0.5220
Epoch 045 | Loss: 1.9986 | T_acc: 0.5934 | N_acc: 0.5330
Epoch 046 | Loss: 1.9717 | T_acc: 0.5989 | N_acc: 0.5385
Epoch 047 | Loss: 2.0100 | T_acc: 0.5769 | N_acc: 0.5110
Epoch 048 | Loss: 2.0163 | T_acc: 0.5989 | N_acc: 0.5275
Epoch 049 | Loss: 1.9607 | T_acc: 0.6099 | N_acc: 0.5220
Epoch 050 | Loss: 1.9290 | T_acc: 0.6429 | N_acc: 0.5330
Epoch 051 | Loss: 1.8992 | T_acc: 0.6319 | N_acc: 0.5659
Epoch 052 | Loss: 1.9351 | T_acc: 0.6374 | N_acc: 0.5220
Epoch 053 | Loss: 1.8826 | T_acc: 0.6374 | N_acc: 0.5440
Epoch 054 | Loss: 1.9592 | T_acc: 0.5989 | N_acc: 0.5275
Epoch 055 | Loss: 1.9009 | T_acc: 0.6209 | N_acc: 0.5495
Epoch 056 | Loss: 1.8360 | T_acc: 0.6484 | N_acc: 0.5275
Epoch 057 | Loss: 1.8248 | T_acc: 0.6484 | N_acc: 0.5165
Epoch 058 | Loss: 1.8531 | T_acc: 0.6374 | N_acc: 0.5549
Epoch 059 | Loss: 1.8166 | T_acc: 0.6429 | N_acc: 0.5495
Epoch 060 | Loss: 1.7789 | T_acc: 0.6593 | N_acc: 0.5220
Epoch 061 | Loss: 1.7767 | T_acc: 0.6648 | N_acc: 0.5385
Epoch 062 | Loss: 1.8059 | T_acc: 0.6593 | N_acc: 0.5549
Epoch 063 | Loss: 1.6835 | T_acc: 0.6868 | N_acc: 0.5879
Epoch 064 | Loss: 1.7166 | T_acc: 0.6923 | N_acc: 0.5879
Epoch 065 | Loss: 1.8194 | T_acc: 0.6538 | N_acc: 0.5769
Epoch 066 | Loss: 1.7854 | T_acc: 0.6593 | N_acc: 0.5769
Epoch 067 | Loss: 1.7631 | T_acc: 0.6593 | N_acc: 0.5549
Epoch 068 | Loss: 1.7665 | T_acc: 0.6538 | N_acc: 0.5549
Epoch 069 | Loss: 1.7294 | T_acc: 0.6813 | N_acc: 0.5440
Epoch 070 | Loss: 1.7235 | T_acc: 0.6484 | N_acc: 0.5659
Epoch 071 | Loss: 1.6575 | T_acc: 0.6593 | N_acc: 0.5824
Epoch 072 | Loss: 1.6546 | T_acc: 0.7033 | N_acc: 0.6154
Epoch 073 | Loss: 1.6679 | T_acc: 0.6758 | N_acc: 0.5879
Epoch 074 | Loss: 1.5641 | T_acc: 0.7088 | N_acc: 0.6374
Epoch 075 | Loss: 1.5643 | T_acc: 0.6868 | N_acc: 0.5934
Epoch 076 | Loss: 1.6922 | T_acc: 0.6758 | N_acc: 0.6099
Epoch 077 | Loss: 1.5837 | T_acc: 0.6868 | N_acc: 0.5879
Epoch 078 | Loss: 1.6081 | T_acc: 0.6813 | N_acc: 0.6044
Epoch 079 | Loss: 1.6107 | T_acc: 0.7143 | N_acc: 0.6209
Epoch 080 | Loss: 1.6137 | T_acc: 0.6978 | N_acc: 0.5659
Epoch 081 | Loss: 1.5823 | T_acc: 0.7033 | N_acc: 0.6099
Epoch 082 | Loss: 1.5662 | T_acc: 0.7253 | N_acc: 0.6209
Epoch 083 | Loss: 1.4975 | T_acc: 0.7143 | N_acc: 0.6264
Epoch 084 | Loss: 1.5958 | T_acc: 0.6923 | N_acc: 0.5604
Epoch 085 | Loss: 1.5184 | T_acc: 0.7308 | N_acc: 0.6484
Epoch 086 | Loss: 1.5278 | T_acc: 0.7143 | N_acc: 0.5934
Epoch 087 | Loss: 1.4815 | T_acc: 0.7253 | N_acc: 0.6374
Epoch 088 | Loss: 1.5109 | T_acc: 0.6978 | N_acc: 0.6044
Epoch 089 | Loss: 1.4991 | T_acc: 0.7198 | N_acc: 0.6264
Epoch 090 | Loss: 1.4397 | T_acc: 0.7527 | N_acc: 0.6264
Epoch 091 | Loss: 1.4722 | T_acc: 0.7253 | N_acc: 0.6319
Epoch 092 | Loss: 1.4900 | T_acc: 0.6978 | N_acc: 0.6429
Epoch 093 | Loss: 1.4706 | T_acc: 0.7033 | N_acc: 0.6484
Epoch 094 | Loss: 1.4340 | T_acc: 0.7198 | N_acc: 0.6374
Epoch 095 | Loss: 1.4808 | T_acc: 0.7143 | N_acc: 0.6374
Epoch 096 | Loss: 1.4670 | T_acc: 0.7198 | N_acc: 0.6264
Epoch 097 | Loss: 1.5094 | T_acc: 0.7088 | N_acc: 0.6099
Epoch 098 | Loss: 1.4409 | T_acc: 0.7143 | N_acc: 0.6538
Epoch 099 | Loss: 1.4945 | T_acc: 0.7418 | N_acc: 0.6264
Epoch 100 | Loss: 1.4327 | T_acc: 0.7198 | N_acc: 0.6484
Epoch 101 | Loss: 1.4730 | T_acc: 0.7088 | N_acc: 0.6484
Epoch 102 | Loss: 1.4401 | T_acc: 0.7363 | N_acc: 0.6319
Epoch 103 | Loss: 1.4502 | T_acc: 0.7637 | N_acc: 0.6484
Epoch 104 | Loss: 1.3985 | T_acc: 0.7527 | N_acc: 0.6484
Epoch 105 | Loss: 1.4670 | T_acc: 0.7308 | N_acc: 0.6374
Epoch 106 | Loss: 1.4373 | T_acc: 0.7308 | N_acc: 0.6484
Epoch 107 | Loss: 1.4202 | T_acc: 0.7418 | N_acc: 0.6209
Epoch 108 | Loss: 1.4422 | T_acc: 0.7363 | N_acc: 0.6484
Epoch 109 | Loss: 1.3669 | T_acc: 0.7527 | N_acc: 0.6593
Epoch 110 | Loss: 1.3757 | T_acc: 0.7582 | N_acc: 0.6648
Epoch 111 | Loss: 1.4031 | T_acc: 0.7527 | N_acc: 0.6923
Epoch 112 | Loss: 1.3606 | T_acc: 0.7582 | N_acc: 0.6758
Epoch 113 | Loss: 1.4372 | T_acc: 0.7253 | N_acc: 0.6429
Epoch 114 | Loss: 1.4152 | T_acc: 0.7308 | N_acc: 0.6429
Epoch 115 | Loss: 1.3882 | T_acc: 0.7418 | N_acc: 0.6868
Epoch 116 | Loss: 1.4655 | T_acc: 0.7143 | N_acc: 0.6154
Epoch 117 | Loss: 1.5257 | T_acc: 0.7033 | N_acc: 0.6429
Epoch 118 | Loss: 1.4440 | T_acc: 0.7582 | N_acc: 0.6154
Epoch 119 | Loss: 1.4143 | T_acc: 0.7363 | N_acc: 0.6209
Epoch 120 | Loss: 1.4135 | T_acc: 0.7088 | N_acc: 0.6538

===== value_small =====

--- T Classification ---
Acc: 0.4348 | BalAcc: 0.2121 | MacroF1: 0.2028
Confidence | Mean: 0.6718 | Median: 0.6553 | Entropy: 0.7429
Confusion matrix (T):
 [[ 0  0  0  1]
 [ 0  0  6  1]
 [ 0  3 18  6]
 [ 0  2  7  2]]

--- N Classification ---
Acc: 0.3478 | BalAcc: 0.2476 | MacroF1: 0.2257
Confidence | Mean: 0.6070 | Median: 0.5579 | Entropy: 0.8951
Confusion matrix (N):
 [[ 4  7  0  0]
 [ 5 11  4  0]
 [ 3  9  1  0]
 [ 1  1  0  0]]

--- Pain Regression ---
MAE: 0.1309 | RMSE: 0.1761 | MSE: 0.0310 | R2: 0.3309 | EVS: 0.3432
Variance | Pred: 0.0088 | True: 0.0464 | ResidualStd: 0.1745

--- VALUE_BIG ---
Original shape: (226, 54)
T class counts: {1: 35, 2: 133, 3: 53, 0: 5}
N class counts: {2: 48, 1: 106, 0: 58, 3: 14}
Train shape (after balancing): (182, 54)
Test shape: (46, 54)
Epoch 001 | Loss: 2.7825 | T_acc: 0.0495 | N_acc: 0.4835
Epoch 002 | Loss: 2.7495 | T_acc: 0.0879 | N_acc: 0.4835
Epoch 003 | Loss: 2.7035 | T_acc: 0.4451 | N_acc: 0.4835
Epoch 004 | Loss: 2.6422 | T_acc: 0.5879 | N_acc: 0.4835
Epoch 005 | Loss: 2.5517 | T_acc: 0.5769 | N_acc: 0.4835
Epoch 006 | Loss: 2.4370 | T_acc: 0.5824 | N_acc: 0.4835
Epoch 007 | Loss: 2.3515 | T_acc: 0.5824 | N_acc: 0.4835
Epoch 008 | Loss: 2.3013 | T_acc: 0.5824 | N_acc: 0.4835
Epoch 009 | Loss: 2.2972 | T_acc: 0.5824 | N_acc: 0.4835
Epoch 010 | Loss: 2.3026 | T_acc: 0.5824 | N_acc: 0.4835
Epoch 011 | Loss: 2.2927 | T_acc: 0.5824 | N_acc: 0.4835
Epoch 012 | Loss: 2.2694 | T_acc: 0.5824 | N_acc: 0.4835
Epoch 013 | Loss: 2.2723 | T_acc: 0.5769 | N_acc: 0.4835
Epoch 014 | Loss: 2.2844 | T_acc: 0.5769 | N_acc: 0.4835
Epoch 015 | Loss: 2.2604 | T_acc: 0.5824 | N_acc: 0.4835
Epoch 016 | Loss: 2.2624 | T_acc: 0.5824 | N_acc: 0.4835
Epoch 017 | Loss: 2.2375 | T_acc: 0.5879 | N_acc: 0.4835
Epoch 018 | Loss: 2.2361 | T_acc: 0.5769 | N_acc: 0.4835

/var/folders/ff/flzt5myn3x55cy_nz85y_ynr0000gn/T/ipykernel_18667/2434738068.py:114: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = torch.cuda.amp.GradScaler(enabled=use_amp)
/var/folders/ff/flzt5myn3x55cy_nz85y_ynr0000gn/T/ipykernel_18667/2434738068.py:135: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with torch.cuda.amp.autocast(enabled=use_amp):

Epoch 019 | Loss: 2.2118 | T_acc: 0.5769 | N_acc: 0.4835
Epoch 020 | Loss: 2.2250 | T_acc: 0.5824 | N_acc: 0.4835
Epoch 021 | Loss: 2.2296 | T_acc: 0.5824 | N_acc: 0.4835
Epoch 022 | Loss: 2.1842 | T_acc: 0.5879 | N_acc: 0.5055
Epoch 023 | Loss: 2.2116 | T_acc: 0.5879 | N_acc: 0.4835
Epoch 024 | Loss: 2.1613 | T_acc: 0.5989 | N_acc: 0.4890
Epoch 025 | Loss: 2.1792 | T_acc: 0.6044 | N_acc: 0.5055
Epoch 026 | Loss: 2.1769 | T_acc: 0.5934 | N_acc: 0.4945
Epoch 027 | Loss: 2.1790 | T_acc: 0.5769 | N_acc: 0.4945
Epoch 028 | Loss: 2.1439 | T_acc: 0.5879 | N_acc: 0.4890
Epoch 029 | Loss: 2.1258 | T_acc: 0.5989 | N_acc: 0.4945
Epoch 030 | Loss: 2.1045 | T_acc: 0.6154 | N_acc: 0.4890
Epoch 031 | Loss: 2.1224 | T_acc: 0.6099 | N_acc: 0.5110
Epoch 032 | Loss: 2.1272 | T_acc: 0.6044 | N_acc: 0.5000
Epoch 033 | Loss: 2.1039 | T_acc: 0.6044 | N_acc: 0.4780
Epoch 034 | Loss: 2.0864 | T_acc: 0.6154 | N_acc: 0.5110
Epoch 035 | Loss: 2.0789 | T_acc: 0.6538 | N_acc: 0.4945
Epoch 036 | Loss: 2.1012 | T_acc: 0.5934 | N_acc: 0.5055
Epoch 037 | Loss: 2.0375 | T_acc: 0.6099 | N_acc: 0.5110
Epoch 038 | Loss: 2.0794 | T_acc: 0.6264 | N_acc: 0.4890
Epoch 039 | Loss: 2.0450 | T_acc: 0.6264 | N_acc: 0.5110
Epoch 040 | Loss: 2.0397 | T_acc: 0.6099 | N_acc: 0.4780
Epoch 041 | Loss: 2.0797 | T_acc: 0.5824 | N_acc: 0.4725
Epoch 042 | Loss: 2.0540 | T_acc: 0.5989 | N_acc: 0.5165
Epoch 043 | Loss: 2.0182 | T_acc: 0.6099 | N_acc: 0.5220
Epoch 044 | Loss: 2.0077 | T_acc: 0.6319 | N_acc: 0.5110
Epoch 045 | Loss: 1.9648 | T_acc: 0.6484 | N_acc: 0.5275
Epoch 046 | Loss: 1.9750 | T_acc: 0.6429 | N_acc: 0.5440
Epoch 047 | Loss: 1.9677 | T_acc: 0.6264 | N_acc: 0.5055
Epoch 048 | Loss: 1.9026 | T_acc: 0.6319 | N_acc: 0.5275
Epoch 049 | Loss: 1.9830 | T_acc: 0.6209 | N_acc: 0.5000
Epoch 050 | Loss: 1.9651 | T_acc: 0.6209 | N_acc: 0.5165
Epoch 051 | Loss: 1.9116 | T_acc: 0.6484 | N_acc: 0.5220
Epoch 052 | Loss: 1.8848 | T_acc: 0.6374 | N_acc: 0.5330
Epoch 053 | Loss: 1.8788 | T_acc: 0.6319 | N_acc: 0.5220
Epoch 054 | Loss: 1.8037 | T_acc: 0.6703 | N_acc: 0.5330
Epoch 055 | Loss: 1.8037 | T_acc: 0.6648 | N_acc: 0.5659
Epoch 056 | Loss: 1.7516 | T_acc: 0.6648 | N_acc: 0.5330
Epoch 057 | Loss: 1.8366 | T_acc: 0.6319 | N_acc: 0.5275
Epoch 058 | Loss: 1.7015 | T_acc: 0.6758 | N_acc: 0.5714
Epoch 059 | Loss: 1.7688 | T_acc: 0.6429 | N_acc: 0.5549
Epoch 060 | Loss: 1.8037 | T_acc: 0.6538 | N_acc: 0.5769
Epoch 061 | Loss: 1.7956 | T_acc: 0.6648 | N_acc: 0.5989
Epoch 062 | Loss: 1.7255 | T_acc: 0.6813 | N_acc: 0.5934
Epoch 063 | Loss: 1.6697 | T_acc: 0.6538 | N_acc: 0.5824
Epoch 064 | Loss: 1.6413 | T_acc: 0.7143 | N_acc: 0.5549
Epoch 065 | Loss: 1.6046 | T_acc: 0.6868 | N_acc: 0.5659
Epoch 066 | Loss: 1.6149 | T_acc: 0.7088 | N_acc: 0.6044
Epoch 067 | Loss: 1.6211 | T_acc: 0.7033 | N_acc: 0.6044
Epoch 068 | Loss: 1.5752 | T_acc: 0.7418 | N_acc: 0.5934
Epoch 069 | Loss: 1.5203 | T_acc: 0.7143 | N_acc: 0.6154
Epoch 070 | Loss: 1.5671 | T_acc: 0.7143 | N_acc: 0.6209
Epoch 071 | Loss: 1.5421 | T_acc: 0.7527 | N_acc: 0.5989
Epoch 072 | Loss: 1.5500 | T_acc: 0.7088 | N_acc: 0.5879
Epoch 073 | Loss: 1.5277 | T_acc: 0.6978 | N_acc: 0.6154
Epoch 074 | Loss: 1.5077 | T_acc: 0.7308 | N_acc: 0.6593
Epoch 075 | Loss: 1.4639 | T_acc: 0.7418 | N_acc: 0.6319
Epoch 076 | Loss: 1.3828 | T_acc: 0.7582 | N_acc: 0.6264
Epoch 077 | Loss: 1.3947 | T_acc: 0.7418 | N_acc: 0.6923
Epoch 078 | Loss: 1.3269 | T_acc: 0.7637 | N_acc: 0.6593
Epoch 079 | Loss: 1.3992 | T_acc: 0.7582 | N_acc: 0.6538
Epoch 080 | Loss: 1.3905 | T_acc: 0.7527 | N_acc: 0.6044
Epoch 081 | Loss: 1.3608 | T_acc: 0.7582 | N_acc: 0.6648
Epoch 082 | Loss: 1.2999 | T_acc: 0.7473 | N_acc: 0.6868
Epoch 083 | Loss: 1.3632 | T_acc: 0.7473 | N_acc: 0.6538
Epoch 084 | Loss: 1.3086 | T_acc: 0.7912 | N_acc: 0.6813
Epoch 085 | Loss: 1.3103 | T_acc: 0.7637 | N_acc: 0.6703
Epoch 086 | Loss: 1.3266 | T_acc: 0.7747 | N_acc: 0.6484
Epoch 087 | Loss: 1.2815 | T_acc: 0.7857 | N_acc: 0.6538
Epoch 088 | Loss: 1.2791 | T_acc: 0.7637 | N_acc: 0.6923
Epoch 089 | Loss: 1.3505 | T_acc: 0.7802 | N_acc: 0.6593
Epoch 090 | Loss: 1.2668 | T_acc: 0.7692 | N_acc: 0.6758
Epoch 091 | Loss: 1.2506 | T_acc: 0.7802 | N_acc: 0.7088
Epoch 092 | Loss: 1.2141 | T_acc: 0.7637 | N_acc: 0.6868
Epoch 093 | Loss: 1.2531 | T_acc: 0.7857 | N_acc: 0.6648
Epoch 094 | Loss: 1.2534 | T_acc: 0.7747 | N_acc: 0.6978
Epoch 095 | Loss: 1.2114 | T_acc: 0.7967 | N_acc: 0.7033
Epoch 096 | Loss: 1.1910 | T_acc: 0.7802 | N_acc: 0.7198
Epoch 097 | Loss: 1.2320 | T_acc: 0.7418 | N_acc: 0.7088
Epoch 098 | Loss: 1.1957 | T_acc: 0.7857 | N_acc: 0.7143
Epoch 099 | Loss: 1.2270 | T_acc: 0.7967 | N_acc: 0.6593
Epoch 100 | Loss: 1.1283 | T_acc: 0.7692 | N_acc: 0.7418
Epoch 101 | Loss: 1.1786 | T_acc: 0.7857 | N_acc: 0.7033
Epoch 102 | Loss: 1.1738 | T_acc: 0.7967 | N_acc: 0.7143
Epoch 103 | Loss: 1.2489 | T_acc: 0.7802 | N_acc: 0.6978
Epoch 104 | Loss: 1.1707 | T_acc: 0.7802 | N_acc: 0.6978
Epoch 105 | Loss: 1.1341 | T_acc: 0.8242 | N_acc: 0.7033
Epoch 106 | Loss: 1.1440 | T_acc: 0.7802 | N_acc: 0.7253
Epoch 107 | Loss: 1.2241 | T_acc: 0.7692 | N_acc: 0.7198
Epoch 108 | Loss: 1.1095 | T_acc: 0.8352 | N_acc: 0.7033
Epoch 109 | Loss: 1.1579 | T_acc: 0.8462 | N_acc: 0.7308
Epoch 110 | Loss: 1.1359 | T_acc: 0.7967 | N_acc: 0.7363
Epoch 111 | Loss: 1.1746 | T_acc: 0.7582 | N_acc: 0.7033
Epoch 112 | Loss: 1.0948 | T_acc: 0.8407 | N_acc: 0.7253
Epoch 113 | Loss: 1.1785 | T_acc: 0.7912 | N_acc: 0.7253
Epoch 114 | Loss: 1.1516 | T_acc: 0.7967 | N_acc: 0.7253
Epoch 115 | Loss: 1.1488 | T_acc: 0.7802 | N_acc: 0.7363
Epoch 116 | Loss: 1.1101 | T_acc: 0.8462 | N_acc: 0.7033
Epoch 117 | Loss: 1.1378 | T_acc: 0.8352 | N_acc: 0.6923
Epoch 118 | Loss: 1.1050 | T_acc: 0.8352 | N_acc: 0.7253
Epoch 119 | Loss: 1.1316 | T_acc: 0.8132 | N_acc: 0.7033
Epoch 120 | Loss: 1.1342 | T_acc: 0.8077 | N_acc: 0.6978

===== value_big =====

--- T Classification ---
Acc: 0.4783 | BalAcc: 0.2706 | MacroF1: 0.2744
Confidence | Mean: 0.7291 | Median: 0.7349 | Entropy: 0.6401
Confusion matrix (T):
 [[ 0  0  1  0]
 [ 0  1  4  2]
 [ 2  1 18  6]
 [ 0  2  6  3]]

--- N Classification ---
Acc: 0.3043 | BalAcc: 0.2057 | MacroF1: 0.1722
Confidence | Mean: 0.6313 | Median: 0.5577 | Entropy: 0.8279
Confusion matrix (N):
 [[ 3  8  0  0]
 [ 6 11  3  0]
 [ 3 10  0  0]
 [ 2  0  0  0]]

--- Pain Regression ---
MAE: 0.1075 | RMSE: 0.1375 | MSE: 0.0189 | R2: 0.5922 | EVS: 0.5932
Variance | Pred: 0.0207 | True: 0.0464 | ResidualStd: 0.1373

--- VALUE_ULTRA ---
Original shape: (226, 54)
T class counts: {1: 35, 2: 133, 3: 53, 0: 5}
N class counts: {2: 48, 1: 106, 0: 58, 3: 14}
Train shape (after balancing): (182, 54)
Test shape: (46, 54)
Epoch 001 | Loss: 2.7668 | T_acc: 0.0330 | N_acc: 0.4835
Epoch 002 | Loss: 2.7232 | T_acc: 0.3297 | N_acc: 0.4835
Epoch 003 | Loss: 2.6708 | T_acc: 0.5824 | N_acc: 0.4835
Epoch 004 | Loss: 2.5839 | T_acc: 0.5824 | N_acc: 0.4835
Epoch 005 | Loss: 2.4465 | T_acc: 0.5824 | N_acc: 0.4835
Epoch 006 | Loss: 2.3564 | T_acc: 0.5824 | N_acc: 0.4835
Epoch 007 | Loss: 2.3115 | T_acc: 0.5824 | N_acc: 0.4835
Epoch 008 | Loss: 2.2819 | T_acc: 0.5824 | N_acc: 0.4835
Epoch 009 | Loss: 2.2904 | T_acc: 0.5824 | N_acc: 0.4835
Epoch 010 | Loss: 2.2643 | T_acc: 0.5824 | N_acc: 0.4835
Epoch 011 | Loss: 2.2535 | T_acc: 0.5824 | N_acc: 0.4835
Epoch 012 | Loss: 2.2422 | T_acc: 0.5824 | N_acc: 0.4835
Epoch 013 | Loss: 2.2120 | T_acc: 0.5824 | N_acc: 0.4835

/var/folders/ff/flzt5myn3x55cy_nz85y_ynr0000gn/T/ipykernel_18667/2434738068.py:114: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = torch.cuda.amp.GradScaler(enabled=use_amp)
/var/folders/ff/flzt5myn3x55cy_nz85y_ynr0000gn/T/ipykernel_18667/2434738068.py:135: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with torch.cuda.amp.autocast(enabled=use_amp):

Epoch 014 | Loss: 2.2027 | T_acc: 0.5824 | N_acc: 0.4835
Epoch 015 | Loss: 2.1945 | T_acc: 0.5714 | N_acc: 0.4835
Epoch 016 | Loss: 2.2084 | T_acc: 0.5714 | N_acc: 0.4835
Epoch 017 | Loss: 2.1641 | T_acc: 0.5989 | N_acc: 0.4835
Epoch 018 | Loss: 2.1296 | T_acc: 0.5879 | N_acc: 0.5000
Epoch 019 | Loss: 2.1663 | T_acc: 0.5989 | N_acc: 0.5110
Epoch 020 | Loss: 2.1398 | T_acc: 0.5989 | N_acc: 0.4945
Epoch 021 | Loss: 2.1152 | T_acc: 0.6209 | N_acc: 0.4835
Epoch 022 | Loss: 2.1244 | T_acc: 0.5769 | N_acc: 0.5165
Epoch 023 | Loss: 2.1265 | T_acc: 0.5879 | N_acc: 0.5055
Epoch 024 | Loss: 2.1731 | T_acc: 0.5934 | N_acc: 0.5330
Epoch 025 | Loss: 2.1564 | T_acc: 0.5769 | N_acc: 0.5000
Epoch 026 | Loss: 2.0917 | T_acc: 0.6099 | N_acc: 0.5275
Epoch 027 | Loss: 2.0533 | T_acc: 0.5769 | N_acc: 0.5165
Epoch 028 | Loss: 2.0110 | T_acc: 0.6209 | N_acc: 0.5220
Epoch 029 | Loss: 2.0138 | T_acc: 0.6099 | N_acc: 0.5495
Epoch 030 | Loss: 1.9454 | T_acc: 0.6099 | N_acc: 0.5110
Epoch 031 | Loss: 2.0065 | T_acc: 0.5989 | N_acc: 0.5275
Epoch 032 | Loss: 1.9326 | T_acc: 0.6264 | N_acc: 0.5330
Epoch 033 | Loss: 1.9541 | T_acc: 0.6154 | N_acc: 0.5110
Epoch 034 | Loss: 2.0329 | T_acc: 0.6374 | N_acc: 0.5055
Epoch 035 | Loss: 1.9307 | T_acc: 0.5824 | N_acc: 0.5330
Epoch 036 | Loss: 1.8684 | T_acc: 0.6429 | N_acc: 0.5769
Epoch 037 | Loss: 1.8003 | T_acc: 0.6484 | N_acc: 0.5934
Epoch 038 | Loss: 1.8170 | T_acc: 0.6484 | N_acc: 0.5714
Epoch 039 | Loss: 1.7373 | T_acc: 0.6538 | N_acc: 0.5659
Epoch 040 | Loss: 1.7343 | T_acc: 0.6319 | N_acc: 0.5769
Epoch 041 | Loss: 1.7386 | T_acc: 0.6538 | N_acc: 0.5934
Epoch 042 | Loss: 1.7522 | T_acc: 0.6154 | N_acc: 0.5769
Epoch 043 | Loss: 1.7819 | T_acc: 0.6319 | N_acc: 0.5549
Epoch 044 | Loss: 1.6512 | T_acc: 0.6538 | N_acc: 0.5989
Epoch 045 | Loss: 1.6837 | T_acc: 0.6374 | N_acc: 0.6044
Epoch 046 | Loss: 1.6995 | T_acc: 0.6209 | N_acc: 0.5879
Epoch 047 | Loss: 1.5862 | T_acc: 0.6758 | N_acc: 0.5934
Epoch 048 | Loss: 1.6640 | T_acc: 0.6923 | N_acc: 0.5934
Epoch 049 | Loss: 1.5694 | T_acc: 0.6484 | N_acc: 0.6264
Epoch 050 | Loss: 1.7465 | T_acc: 0.6374 | N_acc: 0.5989
Epoch 051 | Loss: 1.5876 | T_acc: 0.6813 | N_acc: 0.5714
Epoch 052 | Loss: 1.5524 | T_acc: 0.7088 | N_acc: 0.6264
Epoch 053 | Loss: 1.5718 | T_acc: 0.7033 | N_acc: 0.6593
Epoch 054 | Loss: 1.4814 | T_acc: 0.7088 | N_acc: 0.6374
Epoch 055 | Loss: 1.4216 | T_acc: 0.7198 | N_acc: 0.6703
Epoch 056 | Loss: 1.4220 | T_acc: 0.7308 | N_acc: 0.6593
Epoch 057 | Loss: 1.5289 | T_acc: 0.7198 | N_acc: 0.6429
Epoch 058 | Loss: 1.5190 | T_acc: 0.7143 | N_acc: 0.6538
Epoch 059 | Loss: 1.4189 | T_acc: 0.7088 | N_acc: 0.6264
Epoch 060 | Loss: 1.4106 | T_acc: 0.7473 | N_acc: 0.6484
Epoch 061 | Loss: 1.3575 | T_acc: 0.7198 | N_acc: 0.6978
Epoch 062 | Loss: 1.2467 | T_acc: 0.7582 | N_acc: 0.6703
Epoch 063 | Loss: 1.3433 | T_acc: 0.7088 | N_acc: 0.6978
Epoch 064 | Loss: 1.2343 | T_acc: 0.7912 | N_acc: 0.7198
Epoch 065 | Loss: 1.3929 | T_acc: 0.7527 | N_acc: 0.6538
Epoch 066 | Loss: 1.1609 | T_acc: 0.7418 | N_acc: 0.7418
Epoch 067 | Loss: 1.1656 | T_acc: 0.7857 | N_acc: 0.7418
Epoch 068 | Loss: 1.2491 | T_acc: 0.7033 | N_acc: 0.7143
Epoch 069 | Loss: 1.2229 | T_acc: 0.7418 | N_acc: 0.7253
Epoch 070 | Loss: 1.1461 | T_acc: 0.7473 | N_acc: 0.7527
Epoch 071 | Loss: 1.1033 | T_acc: 0.7967 | N_acc: 0.7363
Epoch 072 | Loss: 1.0806 | T_acc: 0.7912 | N_acc: 0.7692
Epoch 073 | Loss: 1.1412 | T_acc: 0.7692 | N_acc: 0.7692
Epoch 074 | Loss: 1.0334 | T_acc: 0.8077 | N_acc: 0.7473
Epoch 075 | Loss: 1.0441 | T_acc: 0.8022 | N_acc: 0.7637
Epoch 076 | Loss: 1.0501 | T_acc: 0.7747 | N_acc: 0.7418
Epoch 077 | Loss: 0.9868 | T_acc: 0.7912 | N_acc: 0.7912
Epoch 078 | Loss: 1.0989 | T_acc: 0.7582 | N_acc: 0.7802
Epoch 079 | Loss: 1.0571 | T_acc: 0.8022 | N_acc: 0.7363
Epoch 080 | Loss: 1.1333 | T_acc: 0.7692 | N_acc: 0.7637
Epoch 081 | Loss: 0.9822 | T_acc: 0.8022 | N_acc: 0.7637
Epoch 082 | Loss: 0.9326 | T_acc: 0.8407 | N_acc: 0.8242
Epoch 083 | Loss: 0.9418 | T_acc: 0.7912 | N_acc: 0.7912
Epoch 084 | Loss: 0.9298 | T_acc: 0.8242 | N_acc: 0.8132
Epoch 085 | Loss: 0.8963 | T_acc: 0.8407 | N_acc: 0.8132
Epoch 086 | Loss: 0.9224 | T_acc: 0.8242 | N_acc: 0.7747
Epoch 087 | Loss: 0.8996 | T_acc: 0.8297 | N_acc: 0.8297
Epoch 088 | Loss: 0.8612 | T_acc: 0.7967 | N_acc: 0.7967
Epoch 089 | Loss: 0.8302 | T_acc: 0.8407 | N_acc: 0.8242
Epoch 090 | Loss: 0.8190 | T_acc: 0.8242 | N_acc: 0.8352
Epoch 091 | Loss: 0.8051 | T_acc: 0.8297 | N_acc: 0.8022
Epoch 092 | Loss: 0.7981 | T_acc: 0.8242 | N_acc: 0.8352
Epoch 093 | Loss: 0.7598 | T_acc: 0.8352 | N_acc: 0.8352
Epoch 094 | Loss: 0.8118 | T_acc: 0.8571 | N_acc: 0.8352
Epoch 095 | Loss: 0.7755 | T_acc: 0.8516 | N_acc: 0.8022
Epoch 096 | Loss: 0.8142 | T_acc: 0.8297 | N_acc: 0.8462
Epoch 097 | Loss: 0.8421 | T_acc: 0.8352 | N_acc: 0.8132
Epoch 098 | Loss: 0.7266 | T_acc: 0.8407 | N_acc: 0.8736
Epoch 099 | Loss: 0.7349 | T_acc: 0.8407 | N_acc: 0.8352
Epoch 100 | Loss: 0.7530 | T_acc: 0.8297 | N_acc: 0.8352
Epoch 101 | Loss: 0.7080 | T_acc: 0.8462 | N_acc: 0.8516
Epoch 102 | Loss: 0.7544 | T_acc: 0.8736 | N_acc: 0.8516
Epoch 103 | Loss: 0.7380 | T_acc: 0.8462 | N_acc: 0.8462
Epoch 104 | Loss: 0.7847 | T_acc: 0.8407 | N_acc: 0.8132
Epoch 105 | Loss: 0.7799 | T_acc: 0.8571 | N_acc: 0.8077
Epoch 106 | Loss: 0.7718 | T_acc: 0.8407 | N_acc: 0.8132
Epoch 107 | Loss: 0.7147 | T_acc: 0.8571 | N_acc: 0.8516
Epoch 108 | Loss: 0.7256 | T_acc: 0.8571 | N_acc: 0.8352
Epoch 109 | Loss: 0.6927 | T_acc: 0.8626 | N_acc: 0.8681
Epoch 110 | Loss: 0.7132 | T_acc: 0.9011 | N_acc: 0.8407
Epoch 111 | Loss: 0.7040 | T_acc: 0.8626 | N_acc: 0.8462
Epoch 112 | Loss: 0.7144 | T_acc: 0.8462 | N_acc: 0.8516
Epoch 113 | Loss: 0.7215 | T_acc: 0.8352 | N_acc: 0.8571
Epoch 114 | Loss: 0.6516 | T_acc: 0.8626 | N_acc: 0.8516
Epoch 115 | Loss: 0.7005 | T_acc: 0.8516 | N_acc: 0.8571
Epoch 116 | Loss: 0.7284 | T_acc: 0.8681 | N_acc: 0.8077
Epoch 117 | Loss: 0.7237 | T_acc: 0.8901 | N_acc: 0.8242
Epoch 118 | Loss: 0.7451 | T_acc: 0.8352 | N_acc: 0.8242
Epoch 119 | Loss: 0.7884 | T_acc: 0.8462 | N_acc: 0.8077
Epoch 120 | Loss: 0.7434 | T_acc: 0.8571 | N_acc: 0.8407

===== value_ultra =====

--- T Classification ---
Acc: 0.3696 | BalAcc: 0.2243 | MacroF1: 0.2281
Confidence | Mean: 0.7715 | Median: 0.7859 | Entropy: 0.5540
Confusion matrix (T):
 [[ 0  0  1  0]
 [ 0  1  6  0]
 [ 2  5 13  7]
 [ 0  0  8  3]]

--- N Classification ---
Acc: 0.3043 | BalAcc: 0.2261 | MacroF1: 0.1962
Confidence | Mean: 0.7309 | Median: 0.7095 | Entropy: 0.6047
Confusion matrix (N):
 [[5 6 0 0]
 [5 9 6 0]
 [4 9 0 0]
 [1 1 0 0]]

--- Pain Regression ---
MAE: 0.1043 | RMSE: 0.1376 | MSE: 0.0189 | R2: 0.5915 | EVS: 0.5948
Variance | Pred: 0.0232 | True: 0.0464 | ResidualStd: 0.1370

--- VPK_SMALL ---
Original shape: (226, 220)
T class counts: {1: 35, 2: 133, 3: 53, 0: 5}
N class counts: {2: 48, 1: 106, 0: 58, 3: 14}
Train shape (after balancing): (182, 220)
Test shape: (46, 220)
Epoch 001 | Loss: 2.6936 | T_acc: 0.5824 | N_acc: 0.4835
Epoch 002 | Loss: 2.6559 | T_acc: 0.5824 | N_acc: 0.4835
Epoch 003 | Loss: 2.6267 | T_acc: 0.5824 | N_acc: 0.4835
Epoch 004 | Loss: 2.6034 | T_acc: 0.5824 | N_acc: 0.4835
Epoch 005 | Loss: 2.5823 | T_acc: 0.5824 | N_acc: 0.4835
Epoch 006 | Loss: 2.5579 | T_acc: 0.5824 | N_acc: 0.4835

/var/folders/ff/flzt5myn3x55cy_nz85y_ynr0000gn/T/ipykernel_18667/2434738068.py:114: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = torch.cuda.amp.GradScaler(enabled=use_amp)
/var/folders/ff/flzt5myn3x55cy_nz85y_ynr0000gn/T/ipykernel_18667/2434738068.py:135: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with torch.cuda.amp.autocast(enabled=use_amp):

Epoch 007 | Loss: 2.5276 | T_acc: 0.5824 | N_acc: 0.4835
Epoch 008 | Loss: 2.4887 | T_acc: 0.5824 | N_acc: 0.4835
Epoch 009 | Loss: 2.4436 | T_acc: 0.5824 | N_acc: 0.4835
Epoch 010 | Loss: 2.4055 | T_acc: 0.5824 | N_acc: 0.4835
Epoch 011 | Loss: 2.3439 | T_acc: 0.5824 | N_acc: 0.4835
Epoch 012 | Loss: 2.3112 | T_acc: 0.5824 | N_acc: 0.4835
Epoch 013 | Loss: 2.2877 | T_acc: 0.5824 | N_acc: 0.4835
Epoch 014 | Loss: 2.2663 | T_acc: 0.5824 | N_acc: 0.4835
Epoch 015 | Loss: 2.2603 | T_acc: 0.5824 | N_acc: 0.4835
Epoch 016 | Loss: 2.2358 | T_acc: 0.5824 | N_acc: 0.4835
Epoch 017 | Loss: 2.2422 | T_acc: 0.5824 | N_acc: 0.4835
Epoch 018 | Loss: 2.2473 | T_acc: 0.5824 | N_acc: 0.4835
Epoch 019 | Loss: 2.2204 | T_acc: 0.5824 | N_acc: 0.4890
Epoch 020 | Loss: 2.2261 | T_acc: 0.5824 | N_acc: 0.4835
Epoch 021 | Loss: 2.2216 | T_acc: 0.5824 | N_acc: 0.4835
Epoch 022 | Loss: 2.2027 | T_acc: 0.5824 | N_acc: 0.4835
Epoch 023 | Loss: 2.1722 | T_acc: 0.5824 | N_acc: 0.4835
Epoch 024 | Loss: 2.1518 | T_acc: 0.5824 | N_acc: 0.5000
Epoch 025 | Loss: 2.1654 | T_acc: 0.5824 | N_acc: 0.4780
Epoch 026 | Loss: 2.1406 | T_acc: 0.5824 | N_acc: 0.4780
Epoch 027 | Loss: 2.1028 | T_acc: 0.5824 | N_acc: 0.4890
Epoch 028 | Loss: 2.1281 | T_acc: 0.5824 | N_acc: 0.5495
Epoch 029 | Loss: 2.0979 | T_acc: 0.6044 | N_acc: 0.5110
Epoch 030 | Loss: 2.0673 | T_acc: 0.6044 | N_acc: 0.5275
Epoch 031 | Loss: 2.0437 | T_acc: 0.6044 | N_acc: 0.5330
Epoch 032 | Loss: 2.0235 | T_acc: 0.6154 | N_acc: 0.5165
Epoch 033 | Loss: 2.0228 | T_acc: 0.5824 | N_acc: 0.5165
Epoch 034 | Loss: 1.9703 | T_acc: 0.6264 | N_acc: 0.5385
Epoch 035 | Loss: 2.0120 | T_acc: 0.5989 | N_acc: 0.5165
Epoch 036 | Loss: 1.9522 | T_acc: 0.6154 | N_acc: 0.5549
Epoch 037 | Loss: 1.9354 | T_acc: 0.6484 | N_acc: 0.5330
Epoch 038 | Loss: 1.9645 | T_acc: 0.6099 | N_acc: 0.5110
Epoch 039 | Loss: 1.9387 | T_acc: 0.6319 | N_acc: 0.4890
Epoch 040 | Loss: 1.9109 | T_acc: 0.6209 | N_acc: 0.5110
Epoch 041 | Loss: 1.8945 | T_acc: 0.6429 | N_acc: 0.5055
Epoch 042 | Loss: 1.8893 | T_acc: 0.6209 | N_acc: 0.5330
Epoch 043 | Loss: 1.8560 | T_acc: 0.6264 | N_acc: 0.5495
Epoch 044 | Loss: 1.8321 | T_acc: 0.6319 | N_acc: 0.5495
Epoch 045 | Loss: 1.8288 | T_acc: 0.6484 | N_acc: 0.5549
Epoch 046 | Loss: 1.8101 | T_acc: 0.6429 | N_acc: 0.5440
Epoch 047 | Loss: 1.8464 | T_acc: 0.6319 | N_acc: 0.5440
Epoch 048 | Loss: 1.8425 | T_acc: 0.6099 | N_acc: 0.5275
Epoch 049 | Loss: 1.8136 | T_acc: 0.6209 | N_acc: 0.5714
Epoch 050 | Loss: 1.8499 | T_acc: 0.6209 | N_acc: 0.5440
Epoch 051 | Loss: 1.8037 | T_acc: 0.6484 | N_acc: 0.5604
Epoch 052 | Loss: 1.7783 | T_acc: 0.6374 | N_acc: 0.5604
Epoch 053 | Loss: 1.7808 | T_acc: 0.6538 | N_acc: 0.5604
Epoch 054 | Loss: 1.7603 | T_acc: 0.6484 | N_acc: 0.5604
Epoch 055 | Loss: 1.7209 | T_acc: 0.6319 | N_acc: 0.5824
Epoch 056 | Loss: 1.6751 | T_acc: 0.6484 | N_acc: 0.5989
Epoch 057 | Loss: 1.7170 | T_acc: 0.6484 | N_acc: 0.5714
Epoch 058 | Loss: 1.7136 | T_acc: 0.6593 | N_acc: 0.5659
Epoch 059 | Loss: 1.7084 | T_acc: 0.6593 | N_acc: 0.5714
Epoch 060 | Loss: 1.6427 | T_acc: 0.6703 | N_acc: 0.5714
Epoch 061 | Loss: 1.6631 | T_acc: 0.6648 | N_acc: 0.6044
Epoch 062 | Loss: 1.6649 | T_acc: 0.6868 | N_acc: 0.5714
Epoch 063 | Loss: 1.6605 | T_acc: 0.6923 | N_acc: 0.6099
Epoch 064 | Loss: 1.6214 | T_acc: 0.6978 | N_acc: 0.5824
Epoch 065 | Loss: 1.6178 | T_acc: 0.6813 | N_acc: 0.5879
Epoch 066 | Loss: 1.5756 | T_acc: 0.7088 | N_acc: 0.5604
Epoch 067 | Loss: 1.5783 | T_acc: 0.6923 | N_acc: 0.5934
Epoch 068 | Loss: 1.5854 | T_acc: 0.7363 | N_acc: 0.6264
Epoch 069 | Loss: 1.6145 | T_acc: 0.6758 | N_acc: 0.5934
Epoch 070 | Loss: 1.6118 | T_acc: 0.6978 | N_acc: 0.6264
Epoch 071 | Loss: 1.5467 | T_acc: 0.6978 | N_acc: 0.6099
Epoch 072 | Loss: 1.5821 | T_acc: 0.7143 | N_acc: 0.5989
Epoch 073 | Loss: 1.5427 | T_acc: 0.7033 | N_acc: 0.6099
Epoch 074 | Loss: 1.5474 | T_acc: 0.6978 | N_acc: 0.6209
Epoch 075 | Loss: 1.5783 | T_acc: 0.6758 | N_acc: 0.5879
Epoch 076 | Loss: 1.5491 | T_acc: 0.7088 | N_acc: 0.6044
Epoch 077 | Loss: 1.5201 | T_acc: 0.6978 | N_acc: 0.6099
Epoch 078 | Loss: 1.5088 | T_acc: 0.6978 | N_acc: 0.6099
Epoch 079 | Loss: 1.4756 | T_acc: 0.7363 | N_acc: 0.6099
Epoch 080 | Loss: 1.4751 | T_acc: 0.7198 | N_acc: 0.6099
Epoch 081 | Loss: 1.4483 | T_acc: 0.6868 | N_acc: 0.6099
Epoch 082 | Loss: 1.4520 | T_acc: 0.7363 | N_acc: 0.6484
Epoch 083 | Loss: 1.4267 | T_acc: 0.7033 | N_acc: 0.6648
Epoch 084 | Loss: 1.4708 | T_acc: 0.6923 | N_acc: 0.5989
Epoch 085 | Loss: 1.4332 | T_acc: 0.7088 | N_acc: 0.6319
Epoch 086 | Loss: 1.3952 | T_acc: 0.7253 | N_acc: 0.6429
Epoch 087 | Loss: 1.4097 | T_acc: 0.7033 | N_acc: 0.6374
Epoch 088 | Loss: 1.3832 | T_acc: 0.7308 | N_acc: 0.6758
Epoch 089 | Loss: 1.3826 | T_acc: 0.7582 | N_acc: 0.6648
Epoch 090 | Loss: 1.4091 | T_acc: 0.7473 | N_acc: 0.6319
Epoch 091 | Loss: 1.4729 | T_acc: 0.7088 | N_acc: 0.6813
Epoch 092 | Loss: 1.3709 | T_acc: 0.7692 | N_acc: 0.6978
Epoch 093 | Loss: 1.4001 | T_acc: 0.7363 | N_acc: 0.6429
Epoch 094 | Loss: 1.4314 | T_acc: 0.7363 | N_acc: 0.6703
Epoch 095 | Loss: 1.4212 | T_acc: 0.7363 | N_acc: 0.6703
Epoch 096 | Loss: 1.3792 | T_acc: 0.7143 | N_acc: 0.6813
Epoch 097 | Loss: 1.3476 | T_acc: 0.7418 | N_acc: 0.6593
Epoch 098 | Loss: 1.3851 | T_acc: 0.7527 | N_acc: 0.6593
Epoch 099 | Loss: 1.3525 | T_acc: 0.7692 | N_acc: 0.6648
Epoch 100 | Loss: 1.4358 | T_acc: 0.7363 | N_acc: 0.6209
Epoch 101 | Loss: 1.4379 | T_acc: 0.7418 | N_acc: 0.6703
Epoch 102 | Loss: 1.4221 | T_acc: 0.7418 | N_acc: 0.6813
Epoch 103 | Loss: 1.4033 | T_acc: 0.7143 | N_acc: 0.6593
Epoch 104 | Loss: 1.3147 | T_acc: 0.7527 | N_acc: 0.7143
Epoch 105 | Loss: 1.3261 | T_acc: 0.7473 | N_acc: 0.6978
Epoch 106 | Loss: 1.2683 | T_acc: 0.7747 | N_acc: 0.6923
Epoch 107 | Loss: 1.4082 | T_acc: 0.7363 | N_acc: 0.6758
Epoch 108 | Loss: 1.3463 | T_acc: 0.7473 | N_acc: 0.6648
Epoch 109 | Loss: 1.3780 | T_acc: 0.7527 | N_acc: 0.6868
Epoch 110 | Loss: 1.3908 | T_acc: 0.7253 | N_acc: 0.6813
Epoch 111 | Loss: 1.2937 | T_acc: 0.7857 | N_acc: 0.6923
Epoch 112 | Loss: 1.3570 | T_acc: 0.7802 | N_acc: 0.6703
Epoch 113 | Loss: 1.3677 | T_acc: 0.7473 | N_acc: 0.6648
Epoch 114 | Loss: 1.3446 | T_acc: 0.7637 | N_acc: 0.6868
Epoch 115 | Loss: 1.3379 | T_acc: 0.7582 | N_acc: 0.6538
Epoch 116 | Loss: 1.3638 | T_acc: 0.7198 | N_acc: 0.6648
Epoch 117 | Loss: 1.3811 | T_acc: 0.7692 | N_acc: 0.6703
Epoch 118 | Loss: 1.3527 | T_acc: 0.7692 | N_acc: 0.6758
Epoch 119 | Loss: 1.3314 | T_acc: 0.7473 | N_acc: 0.6648
Epoch 120 | Loss: 1.3617 | T_acc: 0.7637 | N_acc: 0.6703

===== vpk_small =====

--- T Classification ---
Acc: 0.4783 | BalAcc: 0.2710 | MacroF1: 0.2578
Confidence | Mean: 0.7037 | Median: 0.7183 | Entropy: 0.6438
Confusion matrix (T):
 [[ 0  0  1  0]
 [ 0  0  7  0]
 [ 0  3 17  7]
 [ 0  1  5  5]]

--- N Classification ---
Acc: 0.5000 | BalAcc: 0.3621 | MacroF1: 0.3631
Confidence | Mean: 0.6072 | Median: 0.5690 | Entropy: 0.9129
Confusion matrix (N):
 [[ 4  7  0  0]
 [ 4 14  2  0]
 [ 2  6  5  0]
 [ 0  2  0  0]]

--- Pain Regression ---
MAE: 0.1720 | RMSE: 0.2242 | MSE: 0.0503 | R2: -0.0844 | EVS: -0.0712
Variance | Pred: 0.0049 | True: 0.0464 | ResidualStd: 0.2228

--- VPK_BIG ---
Original shape: (226, 220)
T class counts: {1: 35, 2: 133, 3: 53, 0: 5}
N class counts: {2: 48, 1: 106, 0: 58, 3: 14}
Train shape (after balancing): (182, 220)
Test shape: (46, 220)
Epoch 001 | Loss: 2.7188 | T_acc: 0.5659 | N_acc: 0.4835
Epoch 002 | Loss: 2.6849 | T_acc: 0.5824 | N_acc: 0.4835
Epoch 003 | Loss: 2.6457 | T_acc: 0.5769 | N_acc: 0.4835
Epoch 004 | Loss: 2.6056 | T_acc: 0.5824 | N_acc: 0.4835
Epoch 005 | Loss: 2.5488 | T_acc: 0.5824 | N_acc: 0.4835

/var/folders/ff/flzt5myn3x55cy_nz85y_ynr0000gn/T/ipykernel_18667/2434738068.py:114: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = torch.cuda.amp.GradScaler(enabled=use_amp)
/var/folders/ff/flzt5myn3x55cy_nz85y_ynr0000gn/T/ipykernel_18667/2434738068.py:135: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with torch.cuda.amp.autocast(enabled=use_amp):

Epoch 006 | Loss: 2.4725 | T_acc: 0.5824 | N_acc: 0.4835
Epoch 007 | Loss: 2.3915 | T_acc: 0.5824 | N_acc: 0.4835
Epoch 008 | Loss: 2.3486 | T_acc: 0.5824 | N_acc: 0.4835
Epoch 009 | Loss: 2.3119 | T_acc: 0.5824 | N_acc: 0.4835
Epoch 010 | Loss: 2.2816 | T_acc: 0.5824 | N_acc: 0.4835
Epoch 011 | Loss: 2.2624 | T_acc: 0.5824 | N_acc: 0.4835
Epoch 012 | Loss: 2.2682 | T_acc: 0.5824 | N_acc: 0.4835
Epoch 013 | Loss: 2.2652 | T_acc: 0.5824 | N_acc: 0.4835
Epoch 014 | Loss: 2.2293 | T_acc: 0.5824 | N_acc: 0.4835
Epoch 015 | Loss: 2.2551 | T_acc: 0.5824 | N_acc: 0.4835
Epoch 016 | Loss: 2.2296 | T_acc: 0.5824 | N_acc: 0.4835
Epoch 017 | Loss: 2.2180 | T_acc: 0.5824 | N_acc: 0.4835
Epoch 018 | Loss: 2.2307 | T_acc: 0.5824 | N_acc: 0.4835
Epoch 019 | Loss: 2.2171 | T_acc: 0.5824 | N_acc: 0.4835
Epoch 020 | Loss: 2.2052 | T_acc: 0.5824 | N_acc: 0.4835
Epoch 021 | Loss: 2.1901 | T_acc: 0.5824 | N_acc: 0.5055
Epoch 022 | Loss: 2.1953 | T_acc: 0.5824 | N_acc: 0.5055
Epoch 023 | Loss: 2.1929 | T_acc: 0.5824 | N_acc: 0.4890
Epoch 024 | Loss: 2.1591 | T_acc: 0.5769 | N_acc: 0.5220
Epoch 025 | Loss: 2.1315 | T_acc: 0.5879 | N_acc: 0.5055
Epoch 026 | Loss: 2.1041 | T_acc: 0.5879 | N_acc: 0.4890
Epoch 027 | Loss: 2.0712 | T_acc: 0.5879 | N_acc: 0.4945
Epoch 028 | Loss: 2.0460 | T_acc: 0.5989 | N_acc: 0.5275
Epoch 029 | Loss: 2.0420 | T_acc: 0.5989 | N_acc: 0.5440
Epoch 030 | Loss: 1.9910 | T_acc: 0.5989 | N_acc: 0.5055
Epoch 031 | Loss: 2.0004 | T_acc: 0.6044 | N_acc: 0.5055
Epoch 032 | Loss: 1.9908 | T_acc: 0.6264 | N_acc: 0.5604
Epoch 033 | Loss: 1.9211 | T_acc: 0.6044 | N_acc: 0.5330
Epoch 034 | Loss: 1.9089 | T_acc: 0.6044 | N_acc: 0.5769
Epoch 035 | Loss: 1.9645 | T_acc: 0.6044 | N_acc: 0.5385
Epoch 036 | Loss: 1.9080 | T_acc: 0.5934 | N_acc: 0.5714
Epoch 037 | Loss: 1.8378 | T_acc: 0.6429 | N_acc: 0.5604
Epoch 038 | Loss: 1.7942 | T_acc: 0.6538 | N_acc: 0.5824
Epoch 039 | Loss: 1.7858 | T_acc: 0.6429 | N_acc: 0.5989
Epoch 040 | Loss: 1.7641 | T_acc: 0.6593 | N_acc: 0.6044
Epoch 041 | Loss: 1.7439 | T_acc: 0.6813 | N_acc: 0.5934
Epoch 042 | Loss: 1.7265 | T_acc: 0.6593 | N_acc: 0.5659
Epoch 043 | Loss: 1.6272 | T_acc: 0.6923 | N_acc: 0.6264
Epoch 044 | Loss: 1.7113 | T_acc: 0.6538 | N_acc: 0.5769
Epoch 045 | Loss: 1.7487 | T_acc: 0.6484 | N_acc: 0.6044
Epoch 046 | Loss: 1.6251 | T_acc: 0.7088 | N_acc: 0.6099
Epoch 047 | Loss: 1.6609 | T_acc: 0.6758 | N_acc: 0.6209
Epoch 048 | Loss: 1.6163 | T_acc: 0.6868 | N_acc: 0.6484
Epoch 049 | Loss: 1.5688 | T_acc: 0.6923 | N_acc: 0.6484
Epoch 050 | Loss: 1.6627 | T_acc: 0.6868 | N_acc: 0.6099
Epoch 051 | Loss: 1.5550 | T_acc: 0.6978 | N_acc: 0.6484
Epoch 052 | Loss: 1.5400 | T_acc: 0.6923 | N_acc: 0.6374
Epoch 053 | Loss: 1.5127 | T_acc: 0.6868 | N_acc: 0.6154
Epoch 054 | Loss: 1.5338 | T_acc: 0.6923 | N_acc: 0.6813
Epoch 055 | Loss: 1.4627 | T_acc: 0.6978 | N_acc: 0.6374
Epoch 056 | Loss: 1.4457 | T_acc: 0.6923 | N_acc: 0.6813
Epoch 057 | Loss: 1.4105 | T_acc: 0.7308 | N_acc: 0.6868
Epoch 058 | Loss: 1.4620 | T_acc: 0.7527 | N_acc: 0.6374
Epoch 059 | Loss: 1.4372 | T_acc: 0.7253 | N_acc: 0.6758
Epoch 060 | Loss: 1.4848 | T_acc: 0.7143 | N_acc: 0.6538
Epoch 061 | Loss: 1.4256 | T_acc: 0.7363 | N_acc: 0.6868
Epoch 062 | Loss: 1.3854 | T_acc: 0.7143 | N_acc: 0.6978
Epoch 063 | Loss: 1.3601 | T_acc: 0.7527 | N_acc: 0.6978
Epoch 064 | Loss: 1.3454 | T_acc: 0.7582 | N_acc: 0.6593
Epoch 065 | Loss: 1.3400 | T_acc: 0.7363 | N_acc: 0.6978
Epoch 066 | Loss: 1.2520 | T_acc: 0.7692 | N_acc: 0.7363
Epoch 067 | Loss: 1.2983 | T_acc: 0.7033 | N_acc: 0.6868
Epoch 068 | Loss: 1.2490 | T_acc: 0.7418 | N_acc: 0.7033
Epoch 069 | Loss: 1.2372 | T_acc: 0.7747 | N_acc: 0.7143
Epoch 070 | Loss: 1.2942 | T_acc: 0.7363 | N_acc: 0.6978
Epoch 071 | Loss: 1.2076 | T_acc: 0.8022 | N_acc: 0.6978
Epoch 072 | Loss: 1.1791 | T_acc: 0.7582 | N_acc: 0.7527
Epoch 073 | Loss: 1.2234 | T_acc: 0.7747 | N_acc: 0.7198
Epoch 074 | Loss: 1.1851 | T_acc: 0.7967 | N_acc: 0.7308
Epoch 075 | Loss: 1.1445 | T_acc: 0.7802 | N_acc: 0.7143
Epoch 076 | Loss: 1.1571 | T_acc: 0.7747 | N_acc: 0.7308
Epoch 077 | Loss: 1.1390 | T_acc: 0.7747 | N_acc: 0.7527
Epoch 078 | Loss: 1.1017 | T_acc: 0.7857 | N_acc: 0.7363
Epoch 079 | Loss: 1.1557 | T_acc: 0.7802 | N_acc: 0.6978
Epoch 080 | Loss: 1.0751 | T_acc: 0.7802 | N_acc: 0.7857
Epoch 081 | Loss: 1.0976 | T_acc: 0.7692 | N_acc: 0.7582
Epoch 082 | Loss: 1.1080 | T_acc: 0.7637 | N_acc: 0.7473
Epoch 083 | Loss: 1.1794 | T_acc: 0.7637 | N_acc: 0.7582
Epoch 084 | Loss: 1.1221 | T_acc: 0.8077 | N_acc: 0.7418
Epoch 085 | Loss: 1.0754 | T_acc: 0.8132 | N_acc: 0.7253
Epoch 086 | Loss: 1.0675 | T_acc: 0.7912 | N_acc: 0.7363
Epoch 087 | Loss: 1.0139 | T_acc: 0.8242 | N_acc: 0.8242
Epoch 088 | Loss: 0.9688 | T_acc: 0.8132 | N_acc: 0.7857
Epoch 089 | Loss: 1.0110 | T_acc: 0.7967 | N_acc: 0.7802
Epoch 090 | Loss: 0.9795 | T_acc: 0.8077 | N_acc: 0.7802
Epoch 091 | Loss: 1.0378 | T_acc: 0.7582 | N_acc: 0.7857
Epoch 092 | Loss: 1.0165 | T_acc: 0.8077 | N_acc: 0.7802
Epoch 093 | Loss: 1.1223 | T_acc: 0.7747 | N_acc: 0.7253
Epoch 094 | Loss: 0.9899 | T_acc: 0.8022 | N_acc: 0.7582
Epoch 095 | Loss: 0.9576 | T_acc: 0.8077 | N_acc: 0.7747
Epoch 096 | Loss: 0.9316 | T_acc: 0.8132 | N_acc: 0.8187
Epoch 097 | Loss: 1.0088 | T_acc: 0.8022 | N_acc: 0.7527
Epoch 098 | Loss: 0.9202 | T_acc: 0.8022 | N_acc: 0.7912
Epoch 099 | Loss: 0.9114 | T_acc: 0.8407 | N_acc: 0.7912
Epoch 100 | Loss: 1.0056 | T_acc: 0.8022 | N_acc: 0.7637
Epoch 101 | Loss: 0.9732 | T_acc: 0.8077 | N_acc: 0.7857
Epoch 102 | Loss: 0.9202 | T_acc: 0.7912 | N_acc: 0.8077
Epoch 103 | Loss: 0.8961 | T_acc: 0.8242 | N_acc: 0.7967
Epoch 104 | Loss: 1.0134 | T_acc: 0.8132 | N_acc: 0.7692
Epoch 105 | Loss: 0.9636 | T_acc: 0.8242 | N_acc: 0.7912
Epoch 106 | Loss: 0.9351 | T_acc: 0.8022 | N_acc: 0.8022
Epoch 107 | Loss: 0.8880 | T_acc: 0.7967 | N_acc: 0.8407
Epoch 108 | Loss: 0.9233 | T_acc: 0.7912 | N_acc: 0.8187
Epoch 109 | Loss: 0.9554 | T_acc: 0.7967 | N_acc: 0.7802
Epoch 110 | Loss: 0.9362 | T_acc: 0.7967 | N_acc: 0.8077
Epoch 111 | Loss: 0.9555 | T_acc: 0.8022 | N_acc: 0.8022
Epoch 112 | Loss: 0.9136 | T_acc: 0.8407 | N_acc: 0.7857
Epoch 113 | Loss: 0.9040 | T_acc: 0.8242 | N_acc: 0.8077
Epoch 114 | Loss: 0.9331 | T_acc: 0.7967 | N_acc: 0.8297
Epoch 115 | Loss: 0.9460 | T_acc: 0.8187 | N_acc: 0.7802
Epoch 116 | Loss: 0.9289 | T_acc: 0.8077 | N_acc: 0.8022
Epoch 117 | Loss: 0.8627 | T_acc: 0.8297 | N_acc: 0.8352
Epoch 118 | Loss: 0.9274 | T_acc: 0.8242 | N_acc: 0.7967
Epoch 119 | Loss: 0.9574 | T_acc: 0.7967 | N_acc: 0.7912
Epoch 120 | Loss: 0.8853 | T_acc: 0.8297 | N_acc: 0.8187

===== vpk_big =====

--- T Classification ---
Acc: 0.6522 | BalAcc: 0.4120 | MacroF1: 0.3998
Confidence | Mean: 0.7622 | Median: 0.7899 | Entropy: 0.5475
Confusion matrix (T):
 [[ 0  0  1  0]
 [ 0  1  6  0]
 [ 0  0 21  6]
 [ 0  1  2  8]]

--- N Classification ---
Acc: 0.4130 | BalAcc: 0.3223 | MacroF1: 0.3373
Confidence | Mean: 0.7520 | Median: 0.7481 | Entropy: 0.5950
Confusion matrix (N):
 [[5 6 0 0]
 [4 9 4 3]
 [1 6 5 1]
 [0 2 0 0]]

--- Pain Regression ---
MAE: 0.1739 | RMSE: 0.2230 | MSE: 0.0497 | R2: -0.0725 | EVS: -0.0666
Variance | Pred: 0.0056 | True: 0.0464 | ResidualStd: 0.2224

--- VPK_ULTRA ---
Original shape: (226, 220)
T class counts: {1: 35, 2: 133, 3: 53, 0: 5}
N class counts: {2: 48, 1: 106, 0: 58, 3: 14}
Train shape (after balancing): (182, 220)
Test shape: (46, 220)
Epoch 001 | Loss: 2.8855 | T_acc: 0.0659 | N_acc: 0.3132
Epoch 002 | Loss: 2.7817 | T_acc: 0.1593 | N_acc: 0.4725
Epoch 003 | Loss: 2.6617 | T_acc: 0.3187 | N_acc: 0.4835
Epoch 004 | Loss: 2.5487 | T_acc: 0.5824 | N_acc: 0.4835
Epoch 005 | Loss: 2.4073 | T_acc: 0.5824 | N_acc: 0.4835
Epoch 006 | Loss: 2.3051 | T_acc: 0.5824 | N_acc: 0.4835
Epoch 007 | Loss: 2.2645 | T_acc: 0.5824 | N_acc: 0.4835
Epoch 008 | Loss: 2.2679 | T_acc: 0.5824 | N_acc: 0.4835
Epoch 009 | Loss: 2.2501 | T_acc: 0.5824 | N_acc: 0.4835
Epoch 010 | Loss: 2.2591 | T_acc: 0.5824 | N_acc: 0.4835
Epoch 011 | Loss: 2.2572 | T_acc: 0.5824 | N_acc: 0.4835
Epoch 012 | Loss: 2.2251 | T_acc: 0.5824 | N_acc: 0.4780
Epoch 013 | Loss: 2.2075 | T_acc: 0.5824 | N_acc: 0.4780
Epoch 014 | Loss: 2.1989 | T_acc: 0.5824 | N_acc: 0.4890
Epoch 015 | Loss: 2.1868 | T_acc: 0.5824 | N_acc: 0.4890
Epoch 016 | Loss: 2.1637 | T_acc: 0.5824 | N_acc: 0.5275

/var/folders/ff/flzt5myn3x55cy_nz85y_ynr0000gn/T/ipykernel_18667/2434738068.py:114: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = torch.cuda.amp.GradScaler(enabled=use_amp)
/var/folders/ff/flzt5myn3x55cy_nz85y_ynr0000gn/T/ipykernel_18667/2434738068.py:135: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with torch.cuda.amp.autocast(enabled=use_amp):

Epoch 017 | Loss: 2.1303 | T_acc: 0.5879 | N_acc: 0.5385
Epoch 018 | Loss: 2.0840 | T_acc: 0.6044 | N_acc: 0.5495
Epoch 019 | Loss: 2.0660 | T_acc: 0.6099 | N_acc: 0.5330
Epoch 020 | Loss: 2.1308 | T_acc: 0.5714 | N_acc: 0.5385
Epoch 021 | Loss: 2.1031 | T_acc: 0.5824 | N_acc: 0.5330
Epoch 022 | Loss: 2.2002 | T_acc: 0.6154 | N_acc: 0.4451
Epoch 023 | Loss: 2.0849 | T_acc: 0.6044 | N_acc: 0.4780
Epoch 024 | Loss: 1.9921 | T_acc: 0.5934 | N_acc: 0.5495
Epoch 025 | Loss: 2.0288 | T_acc: 0.5824 | N_acc: 0.5604
Epoch 026 | Loss: 1.9892 | T_acc: 0.6593 | N_acc: 0.5659
Epoch 027 | Loss: 1.9229 | T_acc: 0.6429 | N_acc: 0.5714
Epoch 028 | Loss: 1.8988 | T_acc: 0.6538 | N_acc: 0.5495
Epoch 029 | Loss: 1.8764 | T_acc: 0.6264 | N_acc: 0.5659
Epoch 030 | Loss: 1.8807 | T_acc: 0.5989 | N_acc: 0.5879
Epoch 031 | Loss: 1.8131 | T_acc: 0.6319 | N_acc: 0.5934
Epoch 032 | Loss: 1.8639 | T_acc: 0.6099 | N_acc: 0.6044
Epoch 033 | Loss: 1.7025 | T_acc: 0.6593 | N_acc: 0.6154
Epoch 034 | Loss: 1.7843 | T_acc: 0.6374 | N_acc: 0.5934
Epoch 035 | Loss: 1.7341 | T_acc: 0.6593 | N_acc: 0.6209
Epoch 036 | Loss: 1.7603 | T_acc: 0.6593 | N_acc: 0.5879
Epoch 037 | Loss: 1.6741 | T_acc: 0.6923 | N_acc: 0.6044
Epoch 038 | Loss: 1.7014 | T_acc: 0.6484 | N_acc: 0.5879
Epoch 039 | Loss: 1.6491 | T_acc: 0.6319 | N_acc: 0.6154
Epoch 040 | Loss: 1.6220 | T_acc: 0.6484 | N_acc: 0.6209
Epoch 041 | Loss: 1.6019 | T_acc: 0.6703 | N_acc: 0.6154
Epoch 042 | Loss: 1.5464 | T_acc: 0.6758 | N_acc: 0.6319
Epoch 043 | Loss: 1.5733 | T_acc: 0.6429 | N_acc: 0.6484
Epoch 044 | Loss: 1.5823 | T_acc: 0.6648 | N_acc: 0.6538
Epoch 045 | Loss: 1.4904 | T_acc: 0.6868 | N_acc: 0.6374
Epoch 046 | Loss: 1.5019 | T_acc: 0.6868 | N_acc: 0.6813
Epoch 047 | Loss: 1.4931 | T_acc: 0.6978 | N_acc: 0.6978
Epoch 048 | Loss: 1.4583 | T_acc: 0.7143 | N_acc: 0.7088
Epoch 049 | Loss: 1.4248 | T_acc: 0.7033 | N_acc: 0.6593
Epoch 050 | Loss: 1.4434 | T_acc: 0.7198 | N_acc: 0.6923
Epoch 051 | Loss: 1.4080 | T_acc: 0.7143 | N_acc: 0.6429
Epoch 052 | Loss: 1.4706 | T_acc: 0.7198 | N_acc: 0.6319
Epoch 053 | Loss: 1.4143 | T_acc: 0.6978 | N_acc: 0.6868
Epoch 054 | Loss: 1.4385 | T_acc: 0.6648 | N_acc: 0.6868
Epoch 055 | Loss: 1.3707 | T_acc: 0.7637 | N_acc: 0.6868
Epoch 056 | Loss: 1.2829 | T_acc: 0.6868 | N_acc: 0.7033
Epoch 057 | Loss: 1.2996 | T_acc: 0.7308 | N_acc: 0.7033
Epoch 058 | Loss: 1.3548 | T_acc: 0.7198 | N_acc: 0.6923
Epoch 059 | Loss: 1.2715 | T_acc: 0.7363 | N_acc: 0.6978
Epoch 060 | Loss: 1.2966 | T_acc: 0.7088 | N_acc: 0.7143
Epoch 061 | Loss: 1.2431 | T_acc: 0.7527 | N_acc: 0.6978
Epoch 062 | Loss: 1.1865 | T_acc: 0.7253 | N_acc: 0.7198
Epoch 063 | Loss: 1.1620 | T_acc: 0.7473 | N_acc: 0.7198
Epoch 064 | Loss: 1.1548 | T_acc: 0.7253 | N_acc: 0.7198
Epoch 065 | Loss: 1.2267 | T_acc: 0.7088 | N_acc: 0.7253
Epoch 066 | Loss: 1.1707 | T_acc: 0.7802 | N_acc: 0.7363
Epoch 067 | Loss: 1.1515 | T_acc: 0.7473 | N_acc: 0.7473
Epoch 068 | Loss: 1.0459 | T_acc: 0.7527 | N_acc: 0.7967
Epoch 069 | Loss: 1.1100 | T_acc: 0.7418 | N_acc: 0.7473
Epoch 070 | Loss: 1.1133 | T_acc: 0.7582 | N_acc: 0.7637
Epoch 071 | Loss: 1.0787 | T_acc: 0.7857 | N_acc: 0.7363
Epoch 072 | Loss: 1.0824 | T_acc: 0.7802 | N_acc: 0.7582
Epoch 073 | Loss: 1.0890 | T_acc: 0.7363 | N_acc: 0.7527
Epoch 074 | Loss: 1.0520 | T_acc: 0.8132 | N_acc: 0.7857
Epoch 075 | Loss: 1.0672 | T_acc: 0.7637 | N_acc: 0.7747
Epoch 076 | Loss: 0.9888 | T_acc: 0.7747 | N_acc: 0.8022
Epoch 077 | Loss: 0.9528 | T_acc: 0.7802 | N_acc: 0.7747
Epoch 078 | Loss: 0.9875 | T_acc: 0.7802 | N_acc: 0.8022
Epoch 079 | Loss: 0.8970 | T_acc: 0.8187 | N_acc: 0.7967
Epoch 080 | Loss: 0.9375 | T_acc: 0.8077 | N_acc: 0.7857
Epoch 081 | Loss: 1.0075 | T_acc: 0.7802 | N_acc: 0.7802
Epoch 082 | Loss: 0.9531 | T_acc: 0.7747 | N_acc: 0.7747
Epoch 083 | Loss: 0.8617 | T_acc: 0.8132 | N_acc: 0.8132
Epoch 084 | Loss: 0.9133 | T_acc: 0.7857 | N_acc: 0.7857
Epoch 085 | Loss: 0.9080 | T_acc: 0.7967 | N_acc: 0.7912
Epoch 086 | Loss: 0.8616 | T_acc: 0.8242 | N_acc: 0.8297
Epoch 087 | Loss: 0.9075 | T_acc: 0.7802 | N_acc: 0.7967
Epoch 088 | Loss: 0.8206 | T_acc: 0.8297 | N_acc: 0.8077
Epoch 089 | Loss: 0.8022 | T_acc: 0.8242 | N_acc: 0.8242
Epoch 090 | Loss: 0.8731 | T_acc: 0.7967 | N_acc: 0.8352
Epoch 091 | Loss: 0.8818 | T_acc: 0.7857 | N_acc: 0.7857
Epoch 092 | Loss: 0.7764 | T_acc: 0.8297 | N_acc: 0.8407
Epoch 093 | Loss: 0.7934 | T_acc: 0.8462 | N_acc: 0.8242
Epoch 094 | Loss: 0.7858 | T_acc: 0.8132 | N_acc: 0.8132
Epoch 095 | Loss: 0.7627 | T_acc: 0.8352 | N_acc: 0.8297
Epoch 096 | Loss: 0.7522 | T_acc: 0.8407 | N_acc: 0.8516
Epoch 097 | Loss: 0.7466 | T_acc: 0.8462 | N_acc: 0.8462
Epoch 098 | Loss: 0.8097 | T_acc: 0.7967 | N_acc: 0.8242
Epoch 099 | Loss: 0.7177 | T_acc: 0.8626 | N_acc: 0.8187
Epoch 100 | Loss: 0.7756 | T_acc: 0.8077 | N_acc: 0.8297
Epoch 101 | Loss: 0.7884 | T_acc: 0.8352 | N_acc: 0.8077
Epoch 102 | Loss: 0.7504 | T_acc: 0.8681 | N_acc: 0.8187
Epoch 103 | Loss: 0.7529 | T_acc: 0.8242 | N_acc: 0.8297
Epoch 104 | Loss: 0.7122 | T_acc: 0.8462 | N_acc: 0.8462
Epoch 105 | Loss: 0.7224 | T_acc: 0.8352 | N_acc: 0.8462
Epoch 106 | Loss: 0.7415 | T_acc: 0.8571 | N_acc: 0.8462
Epoch 107 | Loss: 0.7051 | T_acc: 0.8516 | N_acc: 0.8516
Epoch 108 | Loss: 0.7175 | T_acc: 0.8352 | N_acc: 0.8571
Epoch 109 | Loss: 0.7070 | T_acc: 0.8187 | N_acc: 0.8462
Epoch 110 | Loss: 0.7262 | T_acc: 0.8462 | N_acc: 0.8516
Epoch 111 | Loss: 0.7483 | T_acc: 0.8571 | N_acc: 0.8516
Epoch 112 | Loss: 0.7123 | T_acc: 0.8407 | N_acc: 0.8571
Epoch 113 | Loss: 0.7085 | T_acc: 0.8407 | N_acc: 0.8571
Epoch 114 | Loss: 0.7331 | T_acc: 0.8626 | N_acc: 0.8626
Epoch 115 | Loss: 0.7252 | T_acc: 0.8626 | N_acc: 0.8242
Epoch 116 | Loss: 0.7004 | T_acc: 0.8516 | N_acc: 0.8571
Epoch 117 | Loss: 0.7704 | T_acc: 0.8297 | N_acc: 0.8297
Epoch 118 | Loss: 0.7052 | T_acc: 0.8626 | N_acc: 0.8352
Epoch 119 | Loss: 0.7280 | T_acc: 0.8462 | N_acc: 0.8297
Epoch 120 | Loss: 0.7405 | T_acc: 0.8462 | N_acc: 0.8242

===== vpk_ultra =====

--- T Classification ---
Acc: 0.5652 | BalAcc: 0.3745 | MacroF1: 0.3700
Confidence | Mean: 0.7885 | Median: 0.8071 | Entropy: 0.4455
Confusion matrix (T):
 [[ 0  0  1  0]
 [ 0  2  5  0]
 [ 0  1 18  8]
 [ 0  2  3  6]]

--- N Classification ---
Acc: 0.3913 | BalAcc: 0.4053 | MacroF1: 0.3683
Confidence | Mean: 0.7958 | Median: 0.8644 | Entropy: 0.4749
Confusion matrix (N):
 [[4 6 0 1]
 [3 9 6 2]
 [1 7 4 1]
 [0 1 0 1]]

--- Pain Regression ---
MAE: 0.1653 | RMSE: 0.2213 | MSE: 0.0490 | R2: -0.0563 | EVS: -0.0520
Variance | Pred: 0.0095 | True: 0.0464 | ResidualStd: 0.2208

--- ALL_SMALL ---
Original shape: (226, 256)
T class counts: {1: 35, 2: 133, 3: 53, 0: 5}
N class counts: {2: 48, 1: 106, 0: 58, 3: 14}
Train shape (after balancing): (182, 256)
Test shape: (46, 256)
Epoch 001 | Loss: 3.0281 | T_acc: 0.0330 | N_acc: 0.0659
Epoch 002 | Loss: 3.0116 | T_acc: 0.0330 | N_acc: 0.0659
Epoch 003 | Loss: 2.9979 | T_acc: 0.0330 | N_acc: 0.0659
Epoch 004 | Loss: 2.9888 | T_acc: 0.0330 | N_acc: 0.0659
Epoch 005 | Loss: 2.9790 | T_acc: 0.0330 | N_acc: 0.0659
Epoch 006 | Loss: 2.9697 | T_acc: 0.0330 | N_acc: 0.0659
Epoch 007 | Loss: 2.9563 | T_acc: 0.0330 | N_acc: 0.0659
Epoch 008 | Loss: 2.9299 | T_acc: 0.0330 | N_acc: 0.0659
Epoch 009 | Loss: 2.8873 | T_acc: 0.0879 | N_acc: 0.0659
Epoch 010 | Loss: 2.8272 | T_acc: 0.5110 | N_acc: 0.2088
Epoch 011 | Loss: 2.7578 | T_acc: 0.5824 | N_acc: 0.2527
Epoch 012 | Loss: 2.6993 | T_acc: 0.5824 | N_acc: 0.2473
Epoch 013 | Loss: 2.6269 | T_acc: 0.5824 | N_acc: 0.2527
Epoch 014 | Loss: 2.5814 | T_acc: 0.5824 | N_acc: 0.2527
Epoch 015 | Loss: 2.5389 | T_acc: 0.5824 | N_acc: 0.2582
Epoch 016 | Loss: 2.4915 | T_acc: 0.5824 | N_acc: 0.2527
Epoch 017 | Loss: 2.4535 | T_acc: 0.5824 | N_acc: 0.2582
Epoch 018 | Loss: 2.3812 | T_acc: 0.5824 | N_acc: 0.2747
Epoch 019 | Loss: 2.3543 | T_acc: 0.5824 | N_acc: 0.3516
Epoch 020 | Loss: 2.2897 | T_acc: 0.5824 | N_acc: 0.4560
Epoch 021 | Loss: 2.2763 | T_acc: 0.5824 | N_acc: 0.4835
Epoch 022 | Loss: 2.2584 | T_acc: 0.5824 | N_acc: 0.4835

/var/folders/ff/flzt5myn3x55cy_nz85y_ynr0000gn/T/ipykernel_18667/2434738068.py:114: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = torch.cuda.amp.GradScaler(enabled=use_amp)
/var/folders/ff/flzt5myn3x55cy_nz85y_ynr0000gn/T/ipykernel_18667/2434738068.py:135: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with torch.cuda.amp.autocast(enabled=use_amp):

Epoch 023 | Loss: 2.2217 | T_acc: 0.5824 | N_acc: 0.4835
Epoch 024 | Loss: 2.1994 | T_acc: 0.5824 | N_acc: 0.4835
Epoch 025 | Loss: 2.2060 | T_acc: 0.5824 | N_acc: 0.4835
Epoch 026 | Loss: 2.1969 | T_acc: 0.5824 | N_acc: 0.4835
Epoch 027 | Loss: 2.1644 | T_acc: 0.5824 | N_acc: 0.4835
Epoch 028 | Loss: 2.1708 | T_acc: 0.5879 | N_acc: 0.4945
Epoch 029 | Loss: 2.2116 | T_acc: 0.5824 | N_acc: 0.4890
Epoch 030 | Loss: 2.1913 | T_acc: 0.5824 | N_acc: 0.4945
Epoch 031 | Loss: 2.1758 | T_acc: 0.5824 | N_acc: 0.4835
Epoch 032 | Loss: 2.1143 | T_acc: 0.5824 | N_acc: 0.5000
Epoch 033 | Loss: 2.1036 | T_acc: 0.5824 | N_acc: 0.5000
Epoch 034 | Loss: 2.0627 | T_acc: 0.5824 | N_acc: 0.5275
Epoch 035 | Loss: 2.0526 | T_acc: 0.5824 | N_acc: 0.5165
Epoch 036 | Loss: 2.0411 | T_acc: 0.5824 | N_acc: 0.5275
Epoch 037 | Loss: 2.0914 | T_acc: 0.5934 | N_acc: 0.5330
Epoch 038 | Loss: 2.0276 | T_acc: 0.5934 | N_acc: 0.5330
Epoch 039 | Loss: 1.9833 | T_acc: 0.5879 | N_acc: 0.5495
Epoch 040 | Loss: 1.9581 | T_acc: 0.6154 | N_acc: 0.5385
Epoch 041 | Loss: 1.9796 | T_acc: 0.6209 | N_acc: 0.5220
Epoch 042 | Loss: 1.9201 | T_acc: 0.6209 | N_acc: 0.5385
Epoch 043 | Loss: 1.8888 | T_acc: 0.6374 | N_acc: 0.5659
Epoch 044 | Loss: 1.8629 | T_acc: 0.6374 | N_acc: 0.5330
Epoch 045 | Loss: 1.8813 | T_acc: 0.6319 | N_acc: 0.5659
Epoch 046 | Loss: 1.9220 | T_acc: 0.6319 | N_acc: 0.5000
Epoch 047 | Loss: 1.8837 | T_acc: 0.6484 | N_acc: 0.5330
Epoch 048 | Loss: 1.9774 | T_acc: 0.6044 | N_acc: 0.5220
Epoch 049 | Loss: 1.7955 | T_acc: 0.6374 | N_acc: 0.5879
Epoch 050 | Loss: 1.7913 | T_acc: 0.6484 | N_acc: 0.5659
Epoch 051 | Loss: 1.7389 | T_acc: 0.6648 | N_acc: 0.5879
Epoch 052 | Loss: 1.7806 | T_acc: 0.6264 | N_acc: 0.5714
Epoch 053 | Loss: 1.6854 | T_acc: 0.6703 | N_acc: 0.5989
Epoch 054 | Loss: 1.7364 | T_acc: 0.6648 | N_acc: 0.5824
Epoch 055 | Loss: 1.6963 | T_acc: 0.6484 | N_acc: 0.6154
Epoch 056 | Loss: 1.6814 | T_acc: 0.6593 | N_acc: 0.6044
Epoch 057 | Loss: 1.7026 | T_acc: 0.6648 | N_acc: 0.5989
Epoch 058 | Loss: 1.6582 | T_acc: 0.6429 | N_acc: 0.5934
Epoch 059 | Loss: 1.6422 | T_acc: 0.6758 | N_acc: 0.6209
Epoch 060 | Loss: 1.6443 | T_acc: 0.6923 | N_acc: 0.5769
Epoch 061 | Loss: 1.5348 | T_acc: 0.6978 | N_acc: 0.6209
Epoch 062 | Loss: 1.5450 | T_acc: 0.7033 | N_acc: 0.6484
Epoch 063 | Loss: 1.5542 | T_acc: 0.6978 | N_acc: 0.6484
Epoch 064 | Loss: 1.5523 | T_acc: 0.7198 | N_acc: 0.6209
Epoch 065 | Loss: 1.4947 | T_acc: 0.7253 | N_acc: 0.6538
Epoch 066 | Loss: 1.5329 | T_acc: 0.7143 | N_acc: 0.6593
Epoch 067 | Loss: 1.5303 | T_acc: 0.7143 | N_acc: 0.6484
Epoch 068 | Loss: 1.6019 | T_acc: 0.7198 | N_acc: 0.6209
Epoch 069 | Loss: 1.4401 | T_acc: 0.7143 | N_acc: 0.6703
Epoch 070 | Loss: 1.4487 | T_acc: 0.7253 | N_acc: 0.6264
Epoch 071 | Loss: 1.4334 | T_acc: 0.7363 | N_acc: 0.6484
Epoch 072 | Loss: 1.4013 | T_acc: 0.7418 | N_acc: 0.6374
Epoch 073 | Loss: 1.4355 | T_acc: 0.7308 | N_acc: 0.6264
Epoch 074 | Loss: 1.4604 | T_acc: 0.7418 | N_acc: 0.6374
Epoch 075 | Loss: 1.4079 | T_acc: 0.7253 | N_acc: 0.6868
Epoch 076 | Loss: 1.3828 | T_acc: 0.7253 | N_acc: 0.6868
Epoch 077 | Loss: 1.4147 | T_acc: 0.7308 | N_acc: 0.7088
Epoch 078 | Loss: 1.5063 | T_acc: 0.7527 | N_acc: 0.6923
Epoch 079 | Loss: 1.3550 | T_acc: 0.7473 | N_acc: 0.7033
Epoch 080 | Loss: 1.4065 | T_acc: 0.7692 | N_acc: 0.7088
Epoch 081 | Loss: 1.3594 | T_acc: 0.7582 | N_acc: 0.7033
Epoch 082 | Loss: 1.4454 | T_acc: 0.7418 | N_acc: 0.6703
Epoch 083 | Loss: 1.2909 | T_acc: 0.7692 | N_acc: 0.6868
Epoch 084 | Loss: 1.2997 | T_acc: 0.7747 | N_acc: 0.7033
Epoch 085 | Loss: 1.3287 | T_acc: 0.7637 | N_acc: 0.6978
Epoch 086 | Loss: 1.2836 | T_acc: 0.7692 | N_acc: 0.7308
Epoch 087 | Loss: 1.3917 | T_acc: 0.7473 | N_acc: 0.7198
Epoch 088 | Loss: 1.2635 | T_acc: 0.7802 | N_acc: 0.7253
Epoch 089 | Loss: 1.2400 | T_acc: 0.7692 | N_acc: 0.7253
Epoch 090 | Loss: 1.2330 | T_acc: 0.7802 | N_acc: 0.7473
Epoch 091 | Loss: 1.2425 | T_acc: 0.7802 | N_acc: 0.7198
Epoch 092 | Loss: 1.2253 | T_acc: 0.7747 | N_acc: 0.7418
Epoch 093 | Loss: 1.1841 | T_acc: 0.7637 | N_acc: 0.7473
Epoch 094 | Loss: 1.2085 | T_acc: 0.7912 | N_acc: 0.7143
Epoch 095 | Loss: 1.2819 | T_acc: 0.7912 | N_acc: 0.7088
Epoch 096 | Loss: 1.1561 | T_acc: 0.8022 | N_acc: 0.7418
Epoch 097 | Loss: 1.2568 | T_acc: 0.7692 | N_acc: 0.7088
Epoch 098 | Loss: 1.1712 | T_acc: 0.8187 | N_acc: 0.7473
Epoch 099 | Loss: 1.2562 | T_acc: 0.8022 | N_acc: 0.7033
Epoch 100 | Loss: 1.2329 | T_acc: 0.7582 | N_acc: 0.7253
Epoch 101 | Loss: 1.1552 | T_acc: 0.8132 | N_acc: 0.7582
Epoch 102 | Loss: 1.1405 | T_acc: 0.8187 | N_acc: 0.7363
Epoch 103 | Loss: 1.1755 | T_acc: 0.8077 | N_acc: 0.7363
Epoch 104 | Loss: 1.1664 | T_acc: 0.8132 | N_acc: 0.7308
Epoch 105 | Loss: 1.1566 | T_acc: 0.8077 | N_acc: 0.7363
Epoch 106 | Loss: 1.1659 | T_acc: 0.8132 | N_acc: 0.7198
Epoch 107 | Loss: 1.1611 | T_acc: 0.7747 | N_acc: 0.7527
Epoch 108 | Loss: 1.1729 | T_acc: 0.8077 | N_acc: 0.7582
Epoch 109 | Loss: 1.2108 | T_acc: 0.8187 | N_acc: 0.7198
Epoch 110 | Loss: 1.1574 | T_acc: 0.8022 | N_acc: 0.7473
Epoch 111 | Loss: 1.2305 | T_acc: 0.8077 | N_acc: 0.6978
Epoch 112 | Loss: 1.2288 | T_acc: 0.8297 | N_acc: 0.7308
Epoch 113 | Loss: 1.1980 | T_acc: 0.7637 | N_acc: 0.7582
Epoch 114 | Loss: 1.2426 | T_acc: 0.7857 | N_acc: 0.7418
Epoch 115 | Loss: 1.2291 | T_acc: 0.7967 | N_acc: 0.7198
Epoch 116 | Loss: 1.2261 | T_acc: 0.7967 | N_acc: 0.7473
Epoch 117 | Loss: 1.1320 | T_acc: 0.7967 | N_acc: 0.7473
Epoch 118 | Loss: 1.2144 | T_acc: 0.7692 | N_acc: 0.7637
Epoch 119 | Loss: 1.1562 | T_acc: 0.8077 | N_acc: 0.7473
Epoch 120 | Loss: 1.1446 | T_acc: 0.7912 | N_acc: 0.7637

===== all_small =====

--- T Classification ---
Acc: 0.5217 | BalAcc: 0.2761 | MacroF1: 0.2592
Confidence | Mean: 0.7751 | Median: 0.7840 | Entropy: 0.5441
Confusion matrix (T):
 [[ 0  0  1  0]
 [ 0  0  7  0]
 [ 0  1 20  6]
 [ 0  1  6  4]]

--- N Classification ---
Acc: 0.3043 | BalAcc: 0.1817 | MacroF1: 0.1562
Confidence | Mean: 0.6876 | Median: 0.6803 | Entropy: 0.7142
Confusion matrix (N):
 [[ 0  9  1  1]
 [ 5 13  1  1]
 [ 4  8  1  0]
 [ 0  2  0  0]]

--- Pain Regression ---
MAE: 0.1426 | RMSE: 0.1834 | MSE: 0.0336 | R2: 0.2742 | EVS: 0.2790
Variance | Pred: 0.0084 | True: 0.0464 | ResidualStd: 0.1828

--- ALL_BIG ---
Original shape: (226, 256)
T class counts: {1: 35, 2: 133, 3: 53, 0: 5}
N class counts: {2: 48, 1: 106, 0: 58, 3: 14}
Train shape (after balancing): (182, 256)
Test shape: (46, 256)
Epoch 001 | Loss: 2.7631 | T_acc: 0.1099 | N_acc: 0.4835
Epoch 002 | Loss: 2.7145 | T_acc: 0.5000 | N_acc: 0.4835
Epoch 003 | Loss: 2.6643 | T_acc: 0.5769 | N_acc: 0.4835
Epoch 004 | Loss: 2.5965 | T_acc: 0.5824 | N_acc: 0.4835
Epoch 005 | Loss: 2.5175 | T_acc: 0.5824 | N_acc: 0.4835
Epoch 006 | Loss: 2.4271 | T_acc: 0.5824 | N_acc: 0.4835
Epoch 007 | Loss: 2.3506 | T_acc: 0.5824 | N_acc: 0.4835
Epoch 008 | Loss: 2.3184 | T_acc: 0.5824 | N_acc: 0.4835
Epoch 009 | Loss: 2.2798 | T_acc: 0.5824 | N_acc: 0.4835
Epoch 010 | Loss: 2.2897 | T_acc: 0.5824 | N_acc: 0.4835
Epoch 011 | Loss: 2.2553 | T_acc: 0.5824 | N_acc: 0.4835
Epoch 012 | Loss: 2.2387 | T_acc: 0.5824 | N_acc: 0.4835
Epoch 013 | Loss: 2.2148 | T_acc: 0.5824 | N_acc: 0.4835
Epoch 014 | Loss: 2.2435 | T_acc: 0.5824 | N_acc: 0.4780
Epoch 015 | Loss: 2.2260 | T_acc: 0.5824 | N_acc: 0.4890
Epoch 016 | Loss: 2.2216 | T_acc: 0.5824 | N_acc: 0.5000
Epoch 017 | Loss: 2.2169 | T_acc: 0.5824 | N_acc: 0.4780
Epoch 018 | Loss: 2.2073 | T_acc: 0.5824 | N_acc: 0.5165
Epoch 019 | Loss: 2.1648 | T_acc: 0.5824 | N_acc: 0.5110

/var/folders/ff/flzt5myn3x55cy_nz85y_ynr0000gn/T/ipykernel_18667/2434738068.py:114: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = torch.cuda.amp.GradScaler(enabled=use_amp)
/var/folders/ff/flzt5myn3x55cy_nz85y_ynr0000gn/T/ipykernel_18667/2434738068.py:135: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with torch.cuda.amp.autocast(enabled=use_amp):

Epoch 020 | Loss: 2.1668 | T_acc: 0.5824 | N_acc: 0.4670
Epoch 021 | Loss: 2.1568 | T_acc: 0.5824 | N_acc: 0.5220
Epoch 022 | Loss: 2.1678 | T_acc: 0.5824 | N_acc: 0.5055
Epoch 023 | Loss: 2.0987 | T_acc: 0.5824 | N_acc: 0.5220
Epoch 024 | Loss: 2.0898 | T_acc: 0.5824 | N_acc: 0.5440
Epoch 025 | Loss: 2.0855 | T_acc: 0.5824 | N_acc: 0.5385
Epoch 026 | Loss: 2.0719 | T_acc: 0.5879 | N_acc: 0.5385
Epoch 027 | Loss: 2.0866 | T_acc: 0.5824 | N_acc: 0.5275
Epoch 028 | Loss: 2.0279 | T_acc: 0.5714 | N_acc: 0.5165
Epoch 029 | Loss: 1.9494 | T_acc: 0.5989 | N_acc: 0.5769
Epoch 030 | Loss: 1.9634 | T_acc: 0.6044 | N_acc: 0.5549
Epoch 031 | Loss: 2.0303 | T_acc: 0.6209 | N_acc: 0.5495
Epoch 032 | Loss: 1.9132 | T_acc: 0.5989 | N_acc: 0.5659
Epoch 033 | Loss: 1.8842 | T_acc: 0.6429 | N_acc: 0.6044
Epoch 034 | Loss: 1.7848 | T_acc: 0.6429 | N_acc: 0.5714
Epoch 035 | Loss: 1.7363 | T_acc: 0.6703 | N_acc: 0.6374
Epoch 036 | Loss: 1.7982 | T_acc: 0.6868 | N_acc: 0.6044
Epoch 037 | Loss: 1.7735 | T_acc: 0.6484 | N_acc: 0.6099
Epoch 038 | Loss: 1.7546 | T_acc: 0.6648 | N_acc: 0.5934
Epoch 039 | Loss: 1.6976 | T_acc: 0.6923 | N_acc: 0.6154
Epoch 040 | Loss: 1.5996 | T_acc: 0.7033 | N_acc: 0.6429
Epoch 041 | Loss: 1.5894 | T_acc: 0.6923 | N_acc: 0.6319
Epoch 042 | Loss: 1.5037 | T_acc: 0.6648 | N_acc: 0.6593
Epoch 043 | Loss: 1.5124 | T_acc: 0.7088 | N_acc: 0.6429
Epoch 044 | Loss: 1.5100 | T_acc: 0.7143 | N_acc: 0.6429
Epoch 045 | Loss: 1.6350 | T_acc: 0.7198 | N_acc: 0.6374
Epoch 046 | Loss: 1.4415 | T_acc: 0.7198 | N_acc: 0.6648
Epoch 047 | Loss: 1.4196 | T_acc: 0.7418 | N_acc: 0.7088
Epoch 048 | Loss: 1.2661 | T_acc: 0.7747 | N_acc: 0.7033
Epoch 049 | Loss: 1.3500 | T_acc: 0.7637 | N_acc: 0.6484
Epoch 050 | Loss: 1.3794 | T_acc: 0.7033 | N_acc: 0.6868
Epoch 051 | Loss: 1.4334 | T_acc: 0.7582 | N_acc: 0.6538
Epoch 052 | Loss: 1.3562 | T_acc: 0.7473 | N_acc: 0.6648
Epoch 053 | Loss: 1.2892 | T_acc: 0.7637 | N_acc: 0.6813
Epoch 054 | Loss: 1.2625 | T_acc: 0.7747 | N_acc: 0.7088
Epoch 055 | Loss: 1.2086 | T_acc: 0.7802 | N_acc: 0.7363
Epoch 056 | Loss: 1.2327 | T_acc: 0.7363 | N_acc: 0.7308
Epoch 057 | Loss: 1.1641 | T_acc: 0.7857 | N_acc: 0.7088
Epoch 058 | Loss: 1.2383 | T_acc: 0.7857 | N_acc: 0.7253
Epoch 059 | Loss: 1.1700 | T_acc: 0.7637 | N_acc: 0.7033
Epoch 060 | Loss: 1.1327 | T_acc: 0.7747 | N_acc: 0.7418
Epoch 061 | Loss: 1.0267 | T_acc: 0.7967 | N_acc: 0.7582
Epoch 062 | Loss: 1.1023 | T_acc: 0.7857 | N_acc: 0.7692
Epoch 063 | Loss: 1.0696 | T_acc: 0.7912 | N_acc: 0.7802
Epoch 064 | Loss: 1.0092 | T_acc: 0.7967 | N_acc: 0.8242
Epoch 065 | Loss: 1.0514 | T_acc: 0.8187 | N_acc: 0.7747
Epoch 066 | Loss: 1.0443 | T_acc: 0.7967 | N_acc: 0.7582
Epoch 067 | Loss: 0.9672 | T_acc: 0.8077 | N_acc: 0.7857
Epoch 068 | Loss: 0.9286 | T_acc: 0.8077 | N_acc: 0.8132
Epoch 069 | Loss: 0.9212 | T_acc: 0.8132 | N_acc: 0.7802
Epoch 070 | Loss: 0.8740 | T_acc: 0.8297 | N_acc: 0.8022
Epoch 071 | Loss: 0.8592 | T_acc: 0.8077 | N_acc: 0.8297
Epoch 072 | Loss: 0.8918 | T_acc: 0.8242 | N_acc: 0.8022
Epoch 073 | Loss: 0.9004 | T_acc: 0.8352 | N_acc: 0.8077
Epoch 074 | Loss: 0.8237 | T_acc: 0.8242 | N_acc: 0.8297
Epoch 075 | Loss: 0.8307 | T_acc: 0.8077 | N_acc: 0.8077
Epoch 076 | Loss: 0.8889 | T_acc: 0.8132 | N_acc: 0.8242
Epoch 077 | Loss: 0.8032 | T_acc: 0.8571 | N_acc: 0.8187
Epoch 078 | Loss: 0.8108 | T_acc: 0.8571 | N_acc: 0.8132
Epoch 079 | Loss: 0.8232 | T_acc: 0.8462 | N_acc: 0.8407
Epoch 080 | Loss: 0.7331 | T_acc: 0.8352 | N_acc: 0.8462
Epoch 081 | Loss: 0.8229 | T_acc: 0.8407 | N_acc: 0.8132
Epoch 082 | Loss: 0.8296 | T_acc: 0.8516 | N_acc: 0.8791
Epoch 083 | Loss: 0.6907 | T_acc: 0.8407 | N_acc: 0.9066
Epoch 084 | Loss: 0.6473 | T_acc: 0.8681 | N_acc: 0.8846
Epoch 085 | Loss: 0.7149 | T_acc: 0.8132 | N_acc: 0.8571
Epoch 086 | Loss: 0.6167 | T_acc: 0.8956 | N_acc: 0.8791
Epoch 087 | Loss: 0.8087 | T_acc: 0.8681 | N_acc: 0.8352
Epoch 088 | Loss: 0.6197 | T_acc: 0.9066 | N_acc: 0.8736
Epoch 089 | Loss: 0.7228 | T_acc: 0.8462 | N_acc: 0.8407
Epoch 090 | Loss: 0.6931 | T_acc: 0.8681 | N_acc: 0.8736
Epoch 091 | Loss: 0.6283 | T_acc: 0.8571 | N_acc: 0.9066
Epoch 092 | Loss: 0.6951 | T_acc: 0.8407 | N_acc: 0.8571
Epoch 093 | Loss: 0.5896 | T_acc: 0.8791 | N_acc: 0.8736
Epoch 094 | Loss: 0.6539 | T_acc: 0.8516 | N_acc: 0.8846
Epoch 095 | Loss: 0.6182 | T_acc: 0.8571 | N_acc: 0.8736
Epoch 096 | Loss: 0.6115 | T_acc: 0.8791 | N_acc: 0.8681
Epoch 097 | Loss: 0.5905 | T_acc: 0.8956 | N_acc: 0.8846
Epoch 098 | Loss: 0.6487 | T_acc: 0.8681 | N_acc: 0.9121
Epoch 099 | Loss: 0.5297 | T_acc: 0.8956 | N_acc: 0.9121
Epoch 100 | Loss: 0.6064 | T_acc: 0.8736 | N_acc: 0.8736
Epoch 101 | Loss: 0.5176 | T_acc: 0.8901 | N_acc: 0.9011
Epoch 102 | Loss: 0.5426 | T_acc: 0.9066 | N_acc: 0.8956
Epoch 103 | Loss: 0.5692 | T_acc: 0.8956 | N_acc: 0.8626
Epoch 104 | Loss: 0.5499 | T_acc: 0.9066 | N_acc: 0.8791
Epoch 105 | Loss: 0.5620 | T_acc: 0.9011 | N_acc: 0.8791
Epoch 106 | Loss: 0.4953 | T_acc: 0.9176 | N_acc: 0.8846
Epoch 107 | Loss: 0.5311 | T_acc: 0.8901 | N_acc: 0.9011
Epoch 108 | Loss: 0.5637 | T_acc: 0.8407 | N_acc: 0.9121
Epoch 109 | Loss: 0.5651 | T_acc: 0.8791 | N_acc: 0.8791
Epoch 110 | Loss: 0.5922 | T_acc: 0.8681 | N_acc: 0.8901
Epoch 111 | Loss: 0.5532 | T_acc: 0.8791 | N_acc: 0.8956
Epoch 112 | Loss: 0.4807 | T_acc: 0.9066 | N_acc: 0.9121
Epoch 113 | Loss: 0.5979 | T_acc: 0.8846 | N_acc: 0.8791
Epoch 114 | Loss: 0.6003 | T_acc: 0.8626 | N_acc: 0.8791
Epoch 115 | Loss: 0.5510 | T_acc: 0.8736 | N_acc: 0.8846
Epoch 116 | Loss: 0.5664 | T_acc: 0.8901 | N_acc: 0.9011
Epoch 117 | Loss: 0.5923 | T_acc: 0.8626 | N_acc: 0.9011
Epoch 118 | Loss: 0.4696 | T_acc: 0.9011 | N_acc: 0.9341
Epoch 119 | Loss: 0.4790 | T_acc: 0.9121 | N_acc: 0.9121
Epoch 120 | Loss: 0.5417 | T_acc: 0.8956 | N_acc: 0.9231

===== all_big =====

--- T Classification ---
Acc: 0.5217 | BalAcc: 0.2761 | MacroF1: 0.2748
Confidence | Mean: 0.8518 | Median: 0.9146 | Entropy: 0.3712
Confusion matrix (T):
 [[ 0  0  1  0]
 [ 0  0  7  0]
 [ 0  3 20  4]
 [ 0  3  4  4]]

--- N Classification ---
Acc: 0.3696 | BalAcc: 0.2566 | MacroF1: 0.2517
Confidence | Mean: 0.8296 | Median: 0.8808 | Entropy: 0.4330
Confusion matrix (N):
 [[ 3  5  1  2]
 [ 4 12  3  1]
 [ 3  8  2  0]
 [ 0  2  0  0]]

--- Pain Regression ---
MAE: 0.1419 | RMSE: 0.1776 | MSE: 0.0315 | R2: 0.3198 | EVS: 0.3223
Variance | Pred: 0.0136 | True: 0.0464 | ResidualStd: 0.1772

--- ALL_ULTRA ---
Original shape: (226, 256)
T class counts: {1: 35, 2: 133, 3: 53, 0: 5}
N class counts: {2: 48, 1: 106, 0: 58, 3: 14}
Train shape (after balancing): (182, 256)
Test shape: (46, 256)
Epoch 001 | Loss: 2.8362 | T_acc: 0.2308 | N_acc: 0.1319
Epoch 002 | Loss: 2.8001 | T_acc: 0.2308 | N_acc: 0.1868
Epoch 003 | Loss: 2.7425 | T_acc: 0.3407 | N_acc: 0.4560
Epoch 004 | Loss: 2.6082 | T_acc: 0.5879 | N_acc: 0.4835
Epoch 005 | Loss: 2.4257 | T_acc: 0.5824 | N_acc: 0.4835
Epoch 006 | Loss: 2.3362 | T_acc: 0.5824 | N_acc: 0.4835
Epoch 007 | Loss: 2.2930 | T_acc: 0.5824 | N_acc: 0.4835
Epoch 008 | Loss: 2.2820 | T_acc: 0.5824 | N_acc: 0.4835
Epoch 009 | Loss: 2.2572 | T_acc: 0.5824 | N_acc: 0.4835

/var/folders/ff/flzt5myn3x55cy_nz85y_ynr0000gn/T/ipykernel_18667/2434738068.py:114: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = torch.cuda.amp.GradScaler(enabled=use_amp)
/var/folders/ff/flzt5myn3x55cy_nz85y_ynr0000gn/T/ipykernel_18667/2434738068.py:135: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with torch.cuda.amp.autocast(enabled=use_amp):

Epoch 010 | Loss: 2.2638 | T_acc: 0.5824 | N_acc: 0.4835
Epoch 011 | Loss: 2.2470 | T_acc: 0.5824 | N_acc: 0.4835
Epoch 012 | Loss: 2.2456 | T_acc: 0.5824 | N_acc: 0.4835
Epoch 013 | Loss: 2.2274 | T_acc: 0.5824 | N_acc: 0.4835
Epoch 014 | Loss: 2.2010 | T_acc: 0.5824 | N_acc: 0.4835
Epoch 015 | Loss: 2.2297 | T_acc: 0.5824 | N_acc: 0.4835
Epoch 016 | Loss: 2.1976 | T_acc: 0.5769 | N_acc: 0.4835
Epoch 017 | Loss: 2.1815 | T_acc: 0.5879 | N_acc: 0.4890
Epoch 018 | Loss: 2.1573 | T_acc: 0.5879 | N_acc: 0.4835
Epoch 019 | Loss: 2.1635 | T_acc: 0.5934 | N_acc: 0.4835
Epoch 020 | Loss: 2.1242 | T_acc: 0.5989 | N_acc: 0.5110
Epoch 021 | Loss: 2.1083 | T_acc: 0.5934 | N_acc: 0.4890
Epoch 022 | Loss: 2.0313 | T_acc: 0.6154 | N_acc: 0.5330
Epoch 023 | Loss: 2.0781 | T_acc: 0.6374 | N_acc: 0.5110
Epoch 024 | Loss: 1.9808 | T_acc: 0.6264 | N_acc: 0.5055
Epoch 025 | Loss: 1.9891 | T_acc: 0.6099 | N_acc: 0.4615
Epoch 026 | Loss: 1.9375 | T_acc: 0.6099 | N_acc: 0.5275
Epoch 027 | Loss: 1.8575 | T_acc: 0.6648 | N_acc: 0.5275
Epoch 028 | Loss: 1.7870 | T_acc: 0.6703 | N_acc: 0.5495
Epoch 029 | Loss: 1.8284 | T_acc: 0.6648 | N_acc: 0.5275
Epoch 030 | Loss: 1.7455 | T_acc: 0.6703 | N_acc: 0.5879
Epoch 031 | Loss: 1.7313 | T_acc: 0.6593 | N_acc: 0.5659
Epoch 032 | Loss: 1.7345 | T_acc: 0.6813 | N_acc: 0.5934
Epoch 033 | Loss: 1.8275 | T_acc: 0.6264 | N_acc: 0.5549
Epoch 034 | Loss: 1.6935 | T_acc: 0.6484 | N_acc: 0.6319
Epoch 035 | Loss: 1.5902 | T_acc: 0.6593 | N_acc: 0.5989
Epoch 036 | Loss: 1.5348 | T_acc: 0.6923 | N_acc: 0.6319
Epoch 037 | Loss: 1.5451 | T_acc: 0.6813 | N_acc: 0.6429
Epoch 038 | Loss: 1.5187 | T_acc: 0.6923 | N_acc: 0.6374
Epoch 039 | Loss: 1.4854 | T_acc: 0.6923 | N_acc: 0.6484
Epoch 040 | Loss: 1.5034 | T_acc: 0.6923 | N_acc: 0.6429
Epoch 041 | Loss: 1.3920 | T_acc: 0.7363 | N_acc: 0.6868
Epoch 042 | Loss: 1.4345 | T_acc: 0.6813 | N_acc: 0.6099
Epoch 043 | Loss: 1.4232 | T_acc: 0.6703 | N_acc: 0.6484
Epoch 044 | Loss: 1.4418 | T_acc: 0.7143 | N_acc: 0.6484
Epoch 045 | Loss: 1.2788 | T_acc: 0.7527 | N_acc: 0.6813
Epoch 046 | Loss: 1.4141 | T_acc: 0.6868 | N_acc: 0.6923
Epoch 047 | Loss: 1.3277 | T_acc: 0.7253 | N_acc: 0.6648
Epoch 048 | Loss: 1.3528 | T_acc: 0.7143 | N_acc: 0.7088
Epoch 049 | Loss: 1.1408 | T_acc: 0.7473 | N_acc: 0.7363
Epoch 050 | Loss: 1.1791 | T_acc: 0.7747 | N_acc: 0.7253
Epoch 051 | Loss: 1.1544 | T_acc: 0.7637 | N_acc: 0.7088
Epoch 052 | Loss: 1.0588 | T_acc: 0.7527 | N_acc: 0.7198
Epoch 053 | Loss: 1.0224 | T_acc: 0.7912 | N_acc: 0.7363
Epoch 054 | Loss: 1.0161 | T_acc: 0.8352 | N_acc: 0.7582
Epoch 055 | Loss: 1.1246 | T_acc: 0.7527 | N_acc: 0.7363
Epoch 056 | Loss: 1.0417 | T_acc: 0.7418 | N_acc: 0.7637
Epoch 057 | Loss: 0.8993 | T_acc: 0.8187 | N_acc: 0.7802
Epoch 058 | Loss: 0.9327 | T_acc: 0.7747 | N_acc: 0.7967
Epoch 059 | Loss: 0.9902 | T_acc: 0.7692 | N_acc: 0.7857
Epoch 060 | Loss: 1.0109 | T_acc: 0.7692 | N_acc: 0.7912
Epoch 061 | Loss: 1.0566 | T_acc: 0.7857 | N_acc: 0.7747
Epoch 062 | Loss: 0.8569 | T_acc: 0.8736 | N_acc: 0.8022
Epoch 063 | Loss: 0.8812 | T_acc: 0.8022 | N_acc: 0.8242
Epoch 064 | Loss: 0.9279 | T_acc: 0.7912 | N_acc: 0.7582
Epoch 065 | Loss: 0.8622 | T_acc: 0.8132 | N_acc: 0.7802
Epoch 066 | Loss: 0.7912 | T_acc: 0.8516 | N_acc: 0.8022
Epoch 067 | Loss: 0.7785 | T_acc: 0.8681 | N_acc: 0.8187
Epoch 068 | Loss: 0.7528 | T_acc: 0.8626 | N_acc: 0.8462
Epoch 069 | Loss: 0.7041 | T_acc: 0.8352 | N_acc: 0.8352
Epoch 070 | Loss: 0.7195 | T_acc: 0.8462 | N_acc: 0.8462
Epoch 071 | Loss: 0.6695 | T_acc: 0.8791 | N_acc: 0.8516
Epoch 072 | Loss: 0.6641 | T_acc: 0.8407 | N_acc: 0.8626
Epoch 073 | Loss: 0.5532 | T_acc: 0.8901 | N_acc: 0.8901
Epoch 074 | Loss: 0.6286 | T_acc: 0.8626 | N_acc: 0.8736
Epoch 075 | Loss: 0.6065 | T_acc: 0.8791 | N_acc: 0.8462
Epoch 076 | Loss: 0.6721 | T_acc: 0.8626 | N_acc: 0.8297
Epoch 077 | Loss: 0.5594 | T_acc: 0.8956 | N_acc: 0.8681
Epoch 078 | Loss: 0.5485 | T_acc: 0.8736 | N_acc: 0.8846
Epoch 079 | Loss: 0.6471 | T_acc: 0.8571 | N_acc: 0.8571
Epoch 080 | Loss: 0.6046 | T_acc: 0.8736 | N_acc: 0.8626
Epoch 081 | Loss: 0.5708 | T_acc: 0.8791 | N_acc: 0.8681
Epoch 082 | Loss: 0.5177 | T_acc: 0.8516 | N_acc: 0.9066
Epoch 083 | Loss: 0.5783 | T_acc: 0.8901 | N_acc: 0.8626
Epoch 084 | Loss: 0.5540 | T_acc: 0.8846 | N_acc: 0.8846
Epoch 085 | Loss: 0.5303 | T_acc: 0.8736 | N_acc: 0.9066
Epoch 086 | Loss: 0.4606 | T_acc: 0.9011 | N_acc: 0.9396
Epoch 087 | Loss: 0.4494 | T_acc: 0.9121 | N_acc: 0.9341
Epoch 088 | Loss: 0.4649 | T_acc: 0.8956 | N_acc: 0.9231
Epoch 089 | Loss: 0.4071 | T_acc: 0.9286 | N_acc: 0.9011
Epoch 090 | Loss: 0.4456 | T_acc: 0.8956 | N_acc: 0.9286
Epoch 091 | Loss: 0.5075 | T_acc: 0.9121 | N_acc: 0.8901
Epoch 092 | Loss: 0.4656 | T_acc: 0.9011 | N_acc: 0.9231
Epoch 093 | Loss: 0.3894 | T_acc: 0.8901 | N_acc: 0.9505
Epoch 094 | Loss: 0.4187 | T_acc: 0.9121 | N_acc: 0.9066
Epoch 095 | Loss: 0.4198 | T_acc: 0.9011 | N_acc: 0.9121
Epoch 096 | Loss: 0.3802 | T_acc: 0.9231 | N_acc: 0.9451
Epoch 097 | Loss: 0.3839 | T_acc: 0.9451 | N_acc: 0.9505
Epoch 098 | Loss: 0.4431 | T_acc: 0.9066 | N_acc: 0.9231
Epoch 099 | Loss: 0.3566 | T_acc: 0.9396 | N_acc: 0.9121
Epoch 100 | Loss: 0.4074 | T_acc: 0.9011 | N_acc: 0.9396
Epoch 101 | Loss: 0.4521 | T_acc: 0.9176 | N_acc: 0.9231
Epoch 102 | Loss: 0.3931 | T_acc: 0.9011 | N_acc: 0.9560
Epoch 103 | Loss: 0.3805 | T_acc: 0.9231 | N_acc: 0.9451
Epoch 104 | Loss: 0.4389 | T_acc: 0.9121 | N_acc: 0.9011
Epoch 105 | Loss: 0.3238 | T_acc: 0.9286 | N_acc: 0.9396
Epoch 106 | Loss: 0.3943 | T_acc: 0.9066 | N_acc: 0.9396
Epoch 107 | Loss: 0.4127 | T_acc: 0.8846 | N_acc: 0.9396
Epoch 108 | Loss: 0.3535 | T_acc: 0.9341 | N_acc: 0.9231
Epoch 109 | Loss: 0.3411 | T_acc: 0.9505 | N_acc: 0.9286
Epoch 110 | Loss: 0.3543 | T_acc: 0.9286 | N_acc: 0.9560
Epoch 111 | Loss: 0.4159 | T_acc: 0.9011 | N_acc: 0.9341
Epoch 112 | Loss: 0.3615 | T_acc: 0.9176 | N_acc: 0.9396
Epoch 113 | Loss: 0.3596 | T_acc: 0.9451 | N_acc: 0.9121
Epoch 114 | Loss: 0.3823 | T_acc: 0.9286 | N_acc: 0.9176
Epoch 115 | Loss: 0.3172 | T_acc: 0.9505 | N_acc: 0.9231
Epoch 116 | Loss: 0.3590 | T_acc: 0.9286 | N_acc: 0.9286
Epoch 117 | Loss: 0.3818 | T_acc: 0.9176 | N_acc: 0.9176
Epoch 118 | Loss: 0.3516 | T_acc: 0.9176 | N_acc: 0.9451
Epoch 119 | Loss: 0.3392 | T_acc: 0.9286 | N_acc: 0.9341
Epoch 120 | Loss: 0.3389 | T_acc: 0.9286 | N_acc: 0.9341

===== all_ultra =====

--- T Classification ---
Acc: 0.5000 | BalAcc: 0.2399 | MacroF1: 0.2282
Confidence | Mean: 0.8860 | Median: 0.9734 | Entropy: 0.2892
Confusion matrix (T):
 [[ 0  0  1  0]
 [ 0  0  7  0]
 [ 0  2 21  4]
 [ 0  3  6  2]]

--- N Classification ---
Acc: 0.4130 | BalAcc: 0.2954 | MacroF1: 0.2768
Confidence | Mean: 0.9033 | Median: 0.9696 | Entropy: 0.2767
Confusion matrix (N):
 [[ 5  4  1  1]
 [ 3 13  3  1]
 [ 3  9  1  0]
 [ 0  2  0  0]]

--- Pain Regression ---
MAE: 0.1313 | RMSE: 0.1715 | MSE: 0.0294 | R2: 0.3651 | EVS: 0.3709
Variance | Pred: 0.0165 | True: 0.0464 | ResidualStd: 0.1708